import { v } from "convex/values"
import { getAuthUserId } from "@convex-dev/auth/server"
import { mutation, query } from "./_generated/server"

const OWNER_EMAIL="jabari.xai@gmail.com"
async function owner(ctx:any){const id=await getAuthUserId(ctx);if(!id)throw new Error("Authentication required.");return id}
const stage=v.union(v.literal("new"),v.literal("contacted"),v.literal("qualified"),v.literal("won"),v.literal("lost"))
export const list=query({args:{},returns:v.array(v.any()),handler:async(ctx)=>{await owner(ctx);const rows=await ctx.db.query("agentActions").withIndex("by_status_and_createdAt").order("desc").take(100);return Promise.all(rows.map(async a=>({id:a._id,lead_id:a.leadId,lead_name:(await ctx.db.get(a.leadId))?.name||null,action_type:a.type,payload:a.payload,status:a.status,created_at:a.createdAt})))}})
export const create=mutation({args:{leadId:v.id("leads"),type:v.union(v.literal("create_task"),v.literal("add_note"),v.literal("update_stage"),v.literal("create_email_draft")),payload:v.any(),rationale:v.string()},returns:v.id("agentActions"),handler:async(ctx,a)=>{await owner(ctx);const now=Date.now();return ctx.db.insert("agentActions",{leadId:a.leadId,type:a.type,payload:a.payload,status:"pending",rationale:a.rationale,createdAt:now,updatedAt:now})}})
export const setStatus=mutation({args:{actionId:v.id("agentActions"),status:v.union(v.literal("approved"),v.literal("rejected"))},returns:v.null(),handler:async(ctx,a)=>{await owner(ctx);const row=await ctx.db.get(a.actionId);if(!row||row.status!=="pending")throw new Error("Action not found or already processed.");await ctx.db.patch(row._id,{status:a.status,updatedAt:Date.now()});return null}})
export const execute=mutation({args:{actionId:v.id("agentActions")},returns:v.null(),handler:async(ctx,a)=>{await owner(ctx);const row=await ctx.db.get(a.actionId);if(!row||row.status!=="approved")throw new Error("Action must be approved before execution.");const lead=await ctx.db.get(row.leadId);if(!lead)throw new Error("Lead not found.");const p=(row.payload||{}) as any;const now=Date.now();if(row.type==="create_task")await ctx.db.insert("workflowTasks",{leadId:row.leadId,title:String(p.title||"AI follow-up task"),detail:String(p.description||""),status:"open",createdAt:now,updatedAt:now});else if(row.type==="add_note")await ctx.db.insert("crmActivities",{leadId:row.leadId,type:"note",title:"AI action note",detail:String(p.note||""),createdAt:now});else if(row.type==="update_stage"){const stageValue=String(p.stage||"");const valid=["new","contacted","qualified","won","lost"];if(!valid.includes(stageValue))throw new Error("Invalid stage.");await ctx.db.patch(lead._id,{status:stageValue as any,updatedAt:now});await ctx.db.insert("crmActivities",{leadId:row.leadId,type:"status_changed",title:"AI updated lead stage",detail:"Stage changed to "+stageValue,createdAt:now})}else if(row.type==="create_email_draft")await ctx.db.insert("outreachDrafts",{leadId:row.leadId,subject:String(p.subject||""),bodyText:String(p.body||""),status:"draft",createdAt:now,updatedAt:now});await ctx.db.patch(row._id,{status:"executed",executedAt:now,updatedAt:now});return null}})
