import { v } from "convex/values"
import { getAuthUserId } from "@convex-dev/auth/server"
import { mutation, query, type MutationCtx, type QueryCtx } from "./_generated/server"
import { internal } from "./_generated/api"

const OWNER_EMAIL="jabari.xai@gmail.com"
async function owner(ctx:QueryCtx|MutationCtx){const id=await getAuthUserId(ctx);if(!id)throw new Error("Authentication required.");const identity=await ctx.auth.getUserIdentity();const identityEmail=String((identity as any)?.email??"").toLowerCase();if(identityEmail===OWNER_EMAIL)return;const u=await ctx.db.get(id);if(u?.email?.toLowerCase()!==OWNER_EMAIL)throw new Error("Owner access required.")}

export const list=query({args:{},returns:v.array(v.any()),handler:async(ctx)=>{await owner(ctx);return await ctx.db.query("bookingTypes").withIndex("by_updatedAt").order("desc").take(50)}})
export const get=query({args:{bookingTypeId:v.id("bookingTypes")},returns:v.any(),handler:async(ctx,args)=>{const b=await ctx.db.get(args.bookingTypeId);return b?.status==="published"?b:null}})
export const bookings=query({args:{from:v.number(),to:v.number()},returns:v.array(v.any()),handler:async(ctx,args)=>{await owner(ctx);return await ctx.db.query("bookings").withIndex("by_startAt",q=>q.gte("startAt",args.from).lt("startAt",args.to)).order("asc").take(200)}})
export const createType=mutation({args:{name:v.string(),description:v.string(),durationMinutes:v.number(),location:v.string(),meetingUrl:v.optional(v.string()),timezone:v.string()},returns:v.id("bookingTypes"),handler:async(ctx,a)=>{await owner(ctx);if(!a.name.trim())throw new Error("Booking type name is required.");if(a.durationMinutes<15||a.durationMinutes>480)throw new Error("Duration must be between 15 and 480 minutes.");const now=Date.now();return await ctx.db.insert("bookingTypes",{...a,name:a.name.trim(),description:a.description.trim(),status:"draft",createdAt:now,updatedAt:now})}})
export const setStatus=mutation({args:{bookingTypeId:v.id("bookingTypes"),status:v.union(v.literal("draft"),v.literal("published"),v.literal("paused"))},returns:v.null(),handler:async(ctx,a)=>{await owner(ctx);await ctx.db.patch(a.bookingTypeId,{status:a.status,updatedAt:Date.now()});return null}})
export const available=query({args:{bookingTypeId:v.id("bookingTypes"),from:v.number(),to:v.number()},returns:v.array(v.number()),handler:async(ctx,a)=>{const type=await ctx.db.get(a.bookingTypeId);if(!type||type.status!=="published")return[];const duration=type.durationMinutes*60000,existing=await ctx.db.query("bookings").withIndex("by_startAt",q=>q.gte("startAt",a.from).lt("startAt",a.to+duration)).take(500);const out:number[]=[];for(let t=a.from;t<=a.to;t+=30*60000){const d=new Date(t),hour=d.getHours();if(hour<9||hour>=17)continue;const end=t+duration;if(existing.some(x=>x.status!=="cancelled"&&x.startAt<end&&x.endAt>t))continue;out.push(t)}return out.slice(0,80)}})
export const book=mutation({args:{bookingTypeId:v.id("bookingTypes"),name:v.string(),email:v.string(),phone:v.optional(v.string()),company:v.optional(v.string()),notes:v.optional(v.string()),startAt:v.number(),honeypot:v.optional(v.string())},returns:v.object({ok:v.boolean(),bookingId:v.id("bookings")}),handler:async(ctx,a)=>{
 const type=await ctx.db.get(a.bookingTypeId);if(!type||type.status!=="published")throw new Error("This booking page is unavailable.");if(a.honeypot?.trim())throw new Error("Booking rejected.");const email=a.email.trim().toLowerCase(),name=a.name.trim();if(!name||!email.includes("@"))throw new Error("Name and valid email are required.");const endAt=a.startAt+type.durationMinutes*60000;const overlap=await ctx.db.query("bookings").withIndex("by_startAt",q=>q.gte("startAt",a.startAt).lt("startAt",endAt)).take(50);if(overlap.some(x=>x.status!=="cancelled"&&x.startAt<endAt&&x.endAt>a.startAt))throw new Error("That time was just booked. Please choose another slot.");
 const now=Date.now();let contact=await ctx.db.query("contacts").withIndex("by_email",q=>q.eq("email",email)).first();let leadId=contact?.leadId;let contactId=contact?._id;
 if(!contact){const session=await ctx.db.insert("anonymousSessions",{capability:"booking:"+now,createdAt:now,expiresAt:now+86400000,remainingMessages:0});const thread=await ctx.db.insert("chatThreads",{sessionId:session,title:"Booking: "+name,createdAt:now,updatedAt:now,nextOrder:1});leadId=await ctx.db.insert("leads",{threadId:thread,name,email,company:a.company||"",request:"Booked "+type.name,budget:"",timeline:"",status:"new",createdAt:now,updatedAt:now});contactId=await ctx.db.insert("contacts",{name,email,company:a.company||"",phone:a.phone,source:"booking_page",leadId,createdAt:now,updatedAt:now})}
 const bookingId=await ctx.db.insert("bookings",{bookingTypeId:a.bookingTypeId,name,email,phone:a.phone,company:a.company,notes:a.notes,startAt:a.startAt,endAt,status:"scheduled",leadId,contactId,createdAt:now,updatedAt:now});
 if(contactId)await ctx.db.insert("crmActivities",{contactId,leadId,type:"appointment",title:"Booking received",detail:type.name+" · "+new Date(a.startAt).toLocaleString(),createdAt:now});
 if(leadId)await ctx.scheduler.runAfter(0,internal.workflows.executeForLead,{leadId,event:"appointment_booked",status:"new"});
 return {ok:true,bookingId}
}})