import { v } from "convex/values"
import { getAuthUserId } from "@convex-dev/auth/server"
import { mutation, query, type MutationCtx, type QueryCtx } from "./_generated/server"
const OWNER_EMAIL="jabari.xai@gmail.com"
async function owner(ctx:QueryCtx|MutationCtx){const id=await getAuthUserId(ctx);if(!id)throw new Error("Authentication required.");const identity=await ctx.auth.getUserIdentity();const identityEmail=String((identity as any)?.email??"").toLowerCase();if(identityEmail===OWNER_EMAIL)return;const u=await ctx.db.get(id);if(u?.email?.toLowerCase()!==OWNER_EMAIL)throw new Error("Owner access required.")}
const section=v.object({type:v.union(v.literal("hero"),v.literal("text"),v.literal("features"),v.literal("cta")),heading:v.string(),body:v.string()})
export const list=query({args:{},returns:v.array(v.any()),handler:async ctx=>{await owner(ctx);return await ctx.db.query("landingPages").withIndex("by_updatedAt").order("desc").take(50)}})
export const getBySlug=query({args:{slug:v.string()},returns:v.any(),handler:async(ctx,a)=>{const p=await ctx.db.query("landingPages").withIndex("by_slug",q=>q.eq("slug",a.slug)).first();return p?.status==="published"?p:null}})
export const create=mutation({args:{name:v.string(),slug:v.string(),headline:v.string(),subheadline:v.string(),ctaText:v.string(),theme:v.string(),sections:v.array(section)},returns:v.id("landingPages"),handler:async(ctx,a)=>{await owner(ctx);const slug=a.slug.trim().toLowerCase().replace(/[^a-z0-9-]+/g,"-").replace(/^-|-$/g,"");if(!slug)throw new Error("A valid slug is required.");if(await ctx.db.query("landingPages").withIndex("by_slug",q=>q.eq("slug",slug)).first())throw new Error("That slug already exists.");const now=Date.now();return await ctx.db.insert("landingPages",{...a,name:a.name.trim(),slug, status:"draft",createdAt:now,updatedAt:now})}})
export const setStatus=mutation({args:{pageId:v.id("landingPages"),status:v.union(v.literal("draft"),v.literal("published"),v.literal("paused"))},returns:v.null(),handler:async(ctx,a)=>{await owner(ctx);await ctx.db.patch(a.pageId,{status:a.status,updatedAt:Date.now()});return null}})
export const link=mutation({args:{pageId:v.id("landingPages"),formId:v.optional(v.id("leadForms")),bookingTypeId:v.optional(v.id("bookingTypes"))},returns:v.null(),handler:async(ctx,a)=>{await owner(ctx);await ctx.db.patch(a.pageId,{formId:a.formId,bookingTypeId:a.bookingTypeId,updatedAt:Date.now()});return null}})
