import { mutation, query } from "./_generated/server"
import { v } from "convex/values"
import { getAuthUserId } from "@convex-dev/auth/server"

const stageValidator=v.union(v.literal("new"),v.literal("contacted"),v.literal("qualified"),v.literal("proposal"),v.literal("negotiation"),v.literal("won"),v.literal("lost"))
async function owner(ctx:any){const id=await getAuthUserId(ctx);if(!id)throw new Error("Authentication required.");const u=await ctx.db.get(id);if(!u)throw new Error("Owner account not found.");return u}
export const listForOwner=query({args:{},handler:async ctx=>{await owner(ctx);const rows=await ctx.db.query("opportunities").withIndex("by_stage_and_updatedAt").order("desc").take(500);return Promise.all(rows.map(async o=>{const l=await ctx.db.get(o.leadId);const c=o.companyId?await ctx.db.get(o.companyId):null;return {...o,leadName:l?.name??"",leadEmail:l?.email??"",companyName:c?.name??l?.company??""}}))}})
export const createFromLead=mutation({args:{leadId:v.id("leads"),name:v.string(),value:v.number(),probability:v.number(),expectedCloseAt:v.optional(v.number()),notes:v.string()},handler:async(ctx,a)=>{const u=await owner(ctx);const l=await ctx.db.get(a.leadId);if(!l)throw new Error("Lead not found.");if(a.value<0||a.probability<0||a.probability>100)throw new Error("Invalid deal value or probability.");const c=await ctx.db.query("companies").withIndex("by_name",q=>q.eq("name",l.company)).first();const contact=await ctx.db.query("contacts").withIndex("by_email",q=>q.eq("email",l.email.toLowerCase())).first();const now=Date.now();return await ctx.db.insert("opportunities",{leadId:l._id,contactId:contact?._id,companyId:c?._id,name:a.name.trim()||l.request,stage:l.status==="won"?"won":l.status==="lost"?"lost":l.status,value:a.value,probability:a.probability,expectedCloseAt:a.expectedCloseAt,owner:u.email??"Jabari Tech",notes:a.notes,createdAt:now,updatedAt:now})}})
export const update=mutation({args:{opportunityId:v.id("opportunities"),stage:stageValidator,value:v.number(),probability:v.number(),expectedCloseAt:v.optional(v.number()),notes:v.string()},handler:async(ctx,a)=>{await owner(ctx);if(a.value<0||a.probability<0||a.probability>100)throw new Error("Invalid deal value or probability.");const o=await ctx.db.get(a.opportunityId);if(!o)throw new Error("Opportunity not found.");const now=Date.now();await ctx.db.patch(a.opportunityId,{stage:a.stage,value:a.value,probability:a.probability,expectedCloseAt:a.expectedCloseAt,notes:a.notes,updatedAt:now});if(o.stage!==a.stage)await ctx.db.insert("crmActivities",{contactId:o.contactId,leadId:o.leadId,type:"status_changed",title:"Opportunity stage changed",detail:a.stage,createdAt:now});if((a.stage==="won"||a.stage==="lost")&&o.stage!==a.stage)await ctx.db.patch(o.leadId,{status:a.stage,updatedAt:now})}})
export const createFromLeadWithDefaults=mutation({args:{leadId:v.id("leads")},handler:async(ctx,a)=>{const u=await owner(ctx);const l=await ctx.db.get(a.leadId);if(!l)throw new Error("Lead not found.");const existing=await ctx.db.query("opportunities").withIndex("by_leadId",q=>q.eq("leadId",a.leadId)).first();if(existing)return existing._id;const c=await ctx.db.query("companies").withIndex("by_name",q=>q.eq("name",l.company)).first();const contact=await ctx.db.query("contacts").withIndex("by_email",q=>q.eq("email",l.email.toLowerCase())).first();const now=Date.now();return await ctx.db.insert("opportunities",{leadId:l._id,contactId:contact?._id,companyId:c?._id,name:l.request,stage:l.status==="won"?"won":l.status==="lost"?"lost":l.status,value:0,probability:l.status==="qualified"?60:l.status==="contacted"?30:10,owner:u.email??"Jabari Tech",notes:"Created from captured lead.",createdAt:now,updatedAt:now})}})
export const getForLead=query({args:{leadId:v.id("leads")},handler:async(ctx,a)=>{await owner(ctx);return await ctx.db.query("opportunities").withIndex("by_leadId",q=>q.eq("leadId",a.leadId)).first()}})