import { v } from "convex/values"
import { getAuthUserId } from "@convex-dev/auth/server"
import { mutation, query, type MutationCtx, type QueryCtx } from "./_generated/server"
import { internal } from "./_generated/api"
const OWNER_EMAIL="jabari.xai@gmail.com"
async function owner(ctx:QueryCtx|MutationCtx){const id=await getAuthUserId(ctx);if(!id)throw new Error("Authentication required.");const u=await ctx.db.get(id);if(u?.email?.toLowerCase()!==OWNER_EMAIL)throw new Error("Owner access required.")}
export const list=query({args:{},returns:v.array(v.any()),handler:async ctx=>{await owner(ctx);return await ctx.db.query("reviewRequests").withIndex("by_status_and_createdAt").order("desc").take(100)}})
export const create=mutation({args:{name:v.string(),email:v.string(),leadId:v.optional(v.id("leads")),contactId:v.optional(v.id("contacts"))},returns:v.id("reviewRequests"),handler:async(ctx,a)=>{await owner(ctx);if(!a.name.trim()||!a.email.includes("@"))throw new Error("Valid name and email are required.");const now=Date.now();return await ctx.db.insert("reviewRequests",{name:a.name.trim(),email:a.email.trim().toLowerCase(),leadId:a.leadId,contactId:a.contactId,status:"pending",createdAt:now,updatedAt:now})}})
export const markSent=mutation({args:{requestId:v.id("reviewRequests")},returns:v.null(),handler:async(ctx,a)=>{await owner(ctx);const r=await ctx.db.get(a.requestId);if(!r)throw new Error("Review request not found.");const now=Date.now();await ctx.db.patch(r._id,{status:"sent",sentAt:now,updatedAt:now});await ctx.db.insert("crmActivities",{contactId:r.contactId,leadId:r.leadId,type:"note",title:"Review request sent",detail:"Customer was asked for feedback.",createdAt:now});return null}})
export const getPublic=query({args:{id:v.id("reviewRequests")},returns:v.any(),handler:async(ctx,a)=>{const r=await ctx.db.get(a.id);return r&&r.status==="sent"?r:null}})
export const submit=mutation({args:{id:v.id("reviewRequests"),rating:v.number(),feedback:v.string()},returns:v.null(),handler:async(ctx,a)=>{if(a.rating<1||a.rating>5)throw new Error("Rating must be between 1 and 5.");const r=await ctx.db.get(a.id);if(!r||r.status!=="sent")throw new Error("This review request is no longer available.");const now=Date.now();await ctx.db.patch(r._id,{status:"completed",rating:a.rating,feedback:a.feedback.trim(),completedAt:now,updatedAt:now});await ctx.db.insert("crmActivities",{contactId:r.contactId,leadId:r.leadId,type:"note",title:"Customer feedback received",detail:`${a.rating}/5 — ${a.feedback.trim()}`,createdAt:now});if(r.leadId)await ctx.scheduler.runAfter(0,internal.workflows.executeForLead,{leadId:r.leadId,event:"review_completed",status:"completed"});return null}})
