import type { Config } from "@netlify/functions";
import { createRemoteJWKSet, jwtVerify } from "jose";
import { neon } from "@neondatabase/serverless";
const AUTH_URL="https://ep-polished-term-b5053umh.neonauth.c-7.us-east-2.aws.neon.tech/neondb/auth";
const JWKS_URL="https://ep-polished-term-b5053umh.neonauth.c-7.us-east-2.aws.neon.tech/neondb/auth/.well-known/jwks.json";
const OWNER_EMAIL="jabari.tech.org@gmail.com",jwks=createRemoteJWKSet(new URL(JWKS_URL));
const defaults={identity:"You are Jabari Assistant, the AI assistant for Jabari Tech.",services:"Lead qualification, CRM support, prospect research, outreach drafting and workflow assistance.",tone:"Professional, concise, helpful and human.",qualification:"Qualify leads using explicit evidence from their request, budget, timeline and conversation. Never invent intent.",boundaries:"Do not invent facts, expose private data, or send outreach without explicit approval."};
const json=(b:Record<string,unknown>,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json"}});
async function auth(req:Request){const h=req.headers.get("authorization");if(!h?.startsWith("Bearer "))throw new Response(JSON.stringify({error:"Authentication required"}),{status:401});const v=await jwtVerify(h.slice(7),jwks,{issuer:AUTH_URL});if(String(v.payload.email||"").toLowerCase()!==OWNER_EMAIL)throw new Response(JSON.stringify({error:"Owner access required"}),{status:403});}
function db(){const u=Netlify.env.get("DATABASE_URL");if(!u)throw new Error("DATABASE_URL is not configured.");return neon(u)}
export default async(req:Request)=>{try{await auth(req);const sql=db();if(req.method==="GET"){const rows=await sql`SELECT identity,services,tone,qualification,boundaries FROM agent_settings ORDER BY updated_at DESC LIMIT 1`;return json(rows[0]||defaults)}if(req.method==="PUT"){const x=await req.json() as Record<string,string>,now=Date.now();const existing=await sql`SELECT id FROM agent_settings ORDER BY updated_at DESC LIMIT 1`;if(existing[0])await sql`UPDATE agent_settings SET identity=${x.identity||""},services=${x.services||""},tone=${x.tone||""},qualification=${x.qualification||""},boundaries=${x.boundaries||""},updated_at=${now} WHERE id=${existing[0].id}`;else await sql`INSERT INTO agent_settings (id,identity,services,tone,qualification,boundaries,created_at,updated_at) VALUES (${crypto.randomUUID()},${x.identity||""},${x.services||""},${x.tone||""},${x.qualification||""},${x.boundaries||""},${now},${now})`;return json({ok:true})}return json({error:"Method not allowed"},405)}catch(e){if(e instanceof Response)return e;return json({error:e instanceof Error?e.message:"Agent settings failed."},500)}};
export const config:Config={path:"/api/agent-settings"};