import type { Config } from "@netlify/functions";
import { createRemoteJWKSet, jwtVerify } from "jose";
import { neon } from "@neondatabase/serverless";
export const config: Config = { path: "/api/billing" };
const AUTH="https://ep-polished-term-b5053umh.neonauth.c-7.us-east-2.aws.neon.tech/neondb/auth";
const JWKS=createRemoteJWKSet(new URL("https://ep-polished-term-b5053umh.neonauth.c-7.us-east-2.aws.neon.tech/neondb/auth/.well-known/jwks.json"));
const OWNER="jabari.tech.org@gmail.com";
function db(){const u=Netlify.env.get("DATABASE_URL");if(!u)throw new Error("DATABASE_URL is not configured");return neon(u)}
async function owner(req:Request){const h=req.headers.get("authorization");if(!h?.startsWith("Bearer "))throw new Response(JSON.stringify({error:"Authentication required"}),{status:401});const v=await jwtVerify(h.slice(7),JWKS,{issuer:AUTH});if(String(v.payload.email||"").toLowerCase()!==OWNER)throw new Response(JSON.stringify({error:"Owner access required"}),{status:403})}
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json"}});
function emailHtml(inv:any,items:any[],url:string){const rows=items.map(i=>`<tr><td style="padding:10px 0;border-bottom:1px solid #eee">${String(i.description).replace(/[<>&]/g,"")}</td><td style="padding:10px 0;border-bottom:1px solid #eee;text-align:center">${i.quantity}</td><td style="padding:10px 0;border-bottom:1px solid #eee;text-align:right">${inv.currency} ${Number(i.amount).toFixed(2)}</td></tr>`).join("");return `<!doctype html><html><body style="font-family:Arial,sans-serif;background:#f4f4f2;padding:24px"><div style="max-width:680px;margin:auto;background:#fff;border:1px solid #ddd;padding:32px"><div style="font-size:22px;font-weight:800;letter-spacing:3px">JABARI TECH</div><h1>Invoice ${inv.number}</h1><p>Hello ${inv.customer_name},</p><p>Your invoice is ready. The total is <strong>${inv.currency} ${Number(inv.total).toFixed(2)}</strong>.</p><table width="100%" cellspacing="0"><thead><tr><th align="left">Item</th><th>Qty</th><th align="right">Amount</th></tr></thead><tbody>${rows}</tbody></table><p style="margin-top:24px"><a href="${url}" style="display:inline-block;background:#111;color:#fff;padding:14px 20px;text-decoration:none">VIEW & PAY INVOICE</a></p><p style="color:#777;font-size:12px">Payments are processed securely by Paystack.</p></div></body></html>`}
async function sendGmail(inv:any,items:any[],invoiceUrl:string){const base=Netlify.env.get("MACALY_BASE_URL");const token=Netlify.env.get("MACALY_API_TOKEN");const chatId=Netlify.env.get("MACALY_CHAT_ID");if(!base||!token||!chatId)throw new Error("Gmail integration credentials are not configured for Netlify.");const response=await fetch(base.replace(/\/$/,"")+"/api/client-app/composio-execute",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({chatId,action:"execute",toolName:"GMAIL_SEND_EMAIL",appName:"GMAIL",params:{user_id:"me",recipient_email:inv.customer_email,from_email:"jabari.tech.org@gmail.com",subject:`Invoice ${inv.number} — Jabari Tech`,body:emailHtml(inv,items,invoiceUrl),is_html:true}})});const data:any=await response.json();if(!response.ok||data?.result?.successful===false)throw new Error(String(data?.result?.error||data?.error||"Gmail rejected the send request."))}
export default async(req:Request)=>{
 const url=new URL(req.url),action=url.searchParams.get("action")||"list",sql=db();
 if(action==="public"){const id=url.searchParams.get("id");if(!id)return json({error:"Invoice id required"},400);const rows=await sql`SELECT * FROM invoices WHERE id=${id} AND status NOT IN ('draft','void') LIMIT 1`;if(!rows[0])return json({invoice:null});const items=await sql`SELECT id,description,quantity,unit_price AS "unitPrice",amount FROM invoice_items WHERE invoice_id=${id} ORDER BY created_at`;return json({invoice:{...rows[0],items}})}
 if(action==="pay"){const body=await req.json();const id=String(body.invoiceId||"");const rows=await sql`SELECT * FROM invoices WHERE id=${id} LIMIT 1`;const inv:any=rows[0];if(!inv||inv.status!=="sent")return json({error:"Only sent invoices can be paid."},400);const secret=Netlify.env.get("PAYSTACK_SECRET_KEY");if(!secret)return json({error:"Paystack is not configured."},503);const reference=(`jabari-${String(inv.number).toLowerCase()}-${Date.now()}`).replace(/[^a-z0-9.=\-_]/g,"");const site=Netlify.env.get("SITE_URL")||Netlify.env.get("URL")||"";const res=await fetch("https://api.paystack.co/transaction/initialize",{method:"POST",headers:{Authorization:`Bearer ${secret}`,"Content-Type":"application/json"},body:JSON.stringify({email:inv.customer_email,amount:String(Math.round(Number(inv.total)*100)),currency:inv.currency,reference,metadata:{invoiceId:id,invoiceNumber:inv.number},callback_url:`${site}/invoice/${id}`})});const p:any=await res.json();if(!res.ok||!p.status)return json({error:p.message||"Paystack could not initialize payment."},502);await sql`INSERT INTO paystack_payments (id,invoice_id,reference,amount,currency,status,access_code,authorization_url,created_at,updated_at) VALUES (${crypto.randomUUID()},${id},${reference},${Number(inv.total)},${inv.currency},'initialized',${p.data.access_code},${p.data.authorization_url},${Date.now()},${Date.now()})`;return json({authorizationUrl:p.data.authorization_url,reference})}
 await owner(req);
 if(action==="list"){const products=await sql`SELECT id,name,description,price,currency,status,created_at AS "createdAt",updated_at AS "updatedAt" FROM products ORDER BY updated_at DESC LIMIT 100`;const invoices=await sql`SELECT id,number,customer_name AS "customerName",customer_email AS "customerEmail",contact_id AS "contactId",lead_id AS "leadId",opportunity_id AS "opportunityId",status,currency,subtotal,total,due_at AS "dueAt",paid_at AS "paidAt",notes,created_at AS "createdAt",updated_at AS "updatedAt" FROM invoices ORDER BY updated_at DESC LIMIT 100`;return json({products,invoices})}
 const body=req.method==="POST"?await req.json():{};
 if(action==="product-create"){if(!String(body.name||"").trim()||Number(body.price)<0)return json({error:"Valid product name and price are required."},400);const now=Date.now(),id=crypto.randomUUID();await sql`INSERT INTO products (id,name,description,price,currency,status,created_at,updated_at) VALUES (${id},${String(body.name).trim()},${String(body.description||"")},${Number(body.price)},${String(body.currency||"USD")},'active',${now},${now})`;return json({id})}
 if(action==="product-archive"){await sql`UPDATE products SET status='archived',updated_at=${Date.now()} WHERE id=${String(body.id)}`;return json({ok:true})}
 if(action==="invoice-create"){const items=Array.isArray(body.items)?body.items:[];if(!String(body.customerName||"").trim()||!String(body.customerEmail||"").includes("@")||!items.length)return json({error:"Customer and at least one line item are required."},400);const now=Date.now(),id=crypto.randomUUID(),number=`INV-${new Date(now).getFullYear()}-${String(now).slice(-6)}`;let total=0;for(const item of items)total+=Math.max(1,Number(item.quantity)||1)*(Number(item.unitPrice)||0);await sql`INSERT INTO invoices (id,number,customer_name,customer_email,contact_id,lead_id,opportunity_id,status,currency,subtotal,total,notes,created_at,updated_at) VALUES (${id},${number},${String(body.customerName).trim()},${String(body.customerEmail).trim().toLowerCase()},${body.contactId||null},${body.leadId||null},${body.opportunityId||null},'draft',${String(body.currency||"USD")},${total},${total},${String(body.notes||"")},${now},${now})`;for(const item of items){const q=Math.max(1,Number(item.quantity)||1),p=Number(item.unitPrice)||0;await sql`INSERT INTO invoice_items (id,invoice_id,product_id,description,quantity,unit_price,amount,created_at) VALUES (${crypto.randomUUID()},${id},${item.productId||null},${String(item.description)},${q},${p},${q*p},${now})`}return json({id})}
 if(action==="send"){const id=String(body.id||"");const rows=await sql`SELECT * FROM invoices WHERE id=${id} LIMIT 1`;const inv:any=rows[0];if(!inv||inv.status==="paid"||inv.status==="void")return json({error:"This invoice cannot be sent."},400);const items=await sql`SELECT id,description,quantity,amount FROM invoice_items WHERE invoice_id=${id} ORDER BY created_at`;const site=Netlify.env.get("SITE_URL")||Netlify.env.get("URL")||"";await sendGmail(inv,items,`${site}/invoice/${id}`);await sql`UPDATE invoices SET status='sent',updated_at=${Date.now()} WHERE id=${id}`;return json({ok:true})}
 if(action==="set-status"){const id=String(body.id),status=String(body.status);if(!["draft","sent","paid","void"].includes(status))return json({error:"Invalid status"},400);await sql`UPDATE invoices SET status=${status},paid_at=${status==="paid"?Date.now():null},updated_at=${Date.now()} WHERE id=${id}`;return json({ok:true})}
 return json({error:"Unknown action"},400)
};