import type { Config } from "@netlify/functions";
import { createRemoteJWKSet, jwtVerify } from "jose";
import { neon } from "@neondatabase/serverless";

const AUTH="https://ep-polished-term-b5053umh.neonauth.c-7.us-east-2.aws.neon.tech/neondb/auth";
const JWKS=createRemoteJWKSet(new URL(AUTH+"/.well-known/jwks.json"));
const OWNER="jabari.tech.org@gmail.com";
const json=(x:unknown,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json"}});
function db(){const u=Netlify.env.get("DATABASE_URL");if(!u)throw new Error("DATABASE_URL is not configured.");return neon(u);}
async function owner(req:Request){const h=req.headers.get("authorization");if(!h?.startsWith("Bearer "))throw new Response(JSON.stringify({error:"Authentication required."}),{status:401});const {payload}=await jwtVerify(h.slice(7),JWKS,{issuer:AUTH});if(String(payload.email||"").toLowerCase()!==OWNER)throw new Response(JSON.stringify({error:"Owner access required."}),{status:403});}
async function trigger(db:any,leadId:string,status="new"){const flows=await db`select id from workflows where enabled=true and trigger='appointment_booked' and (condition='any' or condition=${status})`;for(const f of flows as any[]){const active=await db`select id from workflow_executions where workflow_id=${f.id} and lead_id=${leadId} and status='active' limit 1`;if(!active.length){const now=Date.now();await db`insert into workflow_executions(id,workflow_id,lead_id,current_step,status,started_at,updated_at) values(${crypto.randomUUID()},${f.id},${leadId},0,'active',${now},${now})`;}}}
export default async function handler(req:Request){
 try{
  const url=new URL(req.url),action=url.searchParams.get("action")||"list",database=db();
  if(action==="public"||action==="available"||action==="book"){const id=url.searchParams.get("bookingTypeId");if(!id)return json({error:"bookingTypeId is required."},400);const type=(await database`select id,name,description,duration_minutes as "durationMinutes",location,meeting_url as "meetingUrl",timezone,status from booking_types where id=${id} limit 1` as any[])[0];if(!type||type.status!=="published")return json({error:"This booking page is unavailable."},404);
   if(action==="public")return json({type});
   if(action==="available"){const from=Number(url.searchParams.get("from")),to=Number(url.searchParams.get("to"));if(!Number.isFinite(from)||!Number.isFinite(to))return json({error:"Invalid date range."},400);const duration=Number(type.durationMinutes)*60000,existing=await database`select start_at as "startAt",end_at as "endAt",status from bookings where start_at>=${from} and start_at<${to+duration}`;const slots:number[]=[];for(let t=from;t<=to;t+=1800000){const d=new Date(t),hour=d.getHours();if(hour<9||hour>=17)continue;const end=t+duration;if(!(existing as any[]).some(x=>x.status!=="cancelled"&&Number(x.startAt)<end&&Number(x.endAt)>t))slots.push(t);}return json({slots:slots.slice(0,80)});}
   const body=await req.json();const source=String(body.source||"booking_page").slice(0,120);if(String(body.honeypot||"").trim())return json({error:"Booking rejected."},400);const name=String(body.name||"").trim(),email=String(body.email||"").trim().toLowerCase(),startAt=Number(body.startAt);if(!name||!email.includes("@")||!Number.isFinite(startAt))return json({error:"Name, valid email and time are required."},400);const endAt=startAt+Number(type.durationMinutes)*60000;const overlap=await database`select id from bookings where start_at>=${startAt} and start_at<${endAt} and status<>'cancelled' limit 50`;if((overlap as any[]).some(x=>x.id))return json({error:"That time was just booked. Please choose another slot."},409);
   const now=Date.now();let contact=(await database`select * from contacts where lower(email)=${email} order by updated_at desc limit 1` as any[])[0];let leadId=contact?.lead_id,contactId=contact?.id;
   if(!contact){leadId=crypto.randomUUID();contactId=crypto.randomUUID();const threadId=crypto.randomUUID();const sessionId=crypto.randomUUID();await database`insert into anonymous_sessions(id,capability,created_at,expires_at,remaining_messages) values(${sessionId},${"booking:"+now},${now},${now+86400000},0)`;await database`insert into chat_threads(id,session_id,title,created_at,updated_at,next_order) values(${threadId},${sessionId},${"Booking: "+name},${now},${now},1)`;await database`insert into leads(id,thread_id,name,email,company,request,budget,timeline,status,created_at,updated_at) values(${leadId},${threadId},${name},${email},${String(body.company||"")},${"Booked "+type.name},"","",'new',${now},${now})`;await database`insert into contacts(id,name,email,company,phone,source,lead_id,created_at,updated_at) values(${contactId},${name},${email},${String(body.company||"")},${body.phone?String(body.phone):null},'booking_page',${leadId},${now},${now})`;}
   const bookingId=crypto.randomUUID();await database`insert into bookings(id,booking_type_id,name,email,phone,company,notes,start_at,end_at,status,lead_id,contact_id,created_at,updated_at) values(${bookingId},${id},${name},${email},${body.phone?String(body.phone):null},${body.company?String(body.company):null},${body.notes?String(body.notes):null},${startAt},${endAt},'scheduled',${leadId},${contactId},${now},${now})`;await database`insert into crm_activities(id,contact_id,lead_id,type,title,detail,created_at) values(${crypto.randomUUID()},${contactId},${leadId},'appointment','Booking received',${type.name+" · "+new Date(startAt).toLocaleString()},${now})`;await trigger(database,leadId,"new");return json({ok:true,bookingId});
  }
  await owner(req);
  if(action==="list"){const types=await database`select id,name,description,duration_minutes as "durationMinutes",location,meeting_url as "meetingUrl",timezone,status,created_at as "createdAt",updated_at as "updatedAt" from booking_types order by updated_at desc limit 50`;return json({types});}
  if(action==="create"){const b=await req.json(),name=String(b.name||"").trim(),duration=Number(b.durationMinutes);if(!name||duration<15||duration>480)return json({error:"Name and duration (15–480 minutes) are required."},400);const now=Date.now(),id=crypto.randomUUID();await database`insert into booking_types(id,name,description,duration_minutes,location,meeting_url,timezone,status,created_at,updated_at) values(${id},${name},${String(b.description||"Schedule a conversation with our team.")},${duration},${String(b.location||"Online")},${b.meetingUrl?String(b.meetingUrl):null},${String(b.timezone||"UTC")},'draft',${now},${now})`;return json({id});}
  if(action==="status"){const b=await req.json();await database`update booking_types set status=${String(b.status)},updated_at=${Date.now()} where id=${String(b.bookingTypeId)}`;return json({ok:true});}
  return json({error:"Unknown action."},400);
 }catch(e){if(e instanceof Response)return e;return json({error:e instanceof Error?e.message:"Request failed."},500);}
}
export const config:Config={path:"/api/bookings"};
