import type { Config } from "@netlify/functions";
import { createRemoteJWKSet, jwtVerify } from "jose";
import { neon } from "@neondatabase/serverless";
import { fireTrigger, processDue } from "./workflow-engine.mts";
const AUTH_URL="https://ep-polished-term-b5053umh.neonauth.c-7.us-east-2.aws.neon.tech/neondb/auth";
const JWKS_URL=AUTH_URL+"/.well-known/jwks.json"; const jwks=createRemoteJWKSet(new URL(JWKS_URL));
const json=(body:Record<string,unknown>,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json"}});
async function auth(req:Request){const h=req.headers.get("authorization");if(!h?.startsWith("Bearer "))throw json({error:"Authentication required"},401);await jwtVerify(h.slice(7),jwks,{issuer:AUTH_URL});}
export default async(req:Request)=>{try{await auth(req);const db=Netlify.env.get("DATABASE_URL");if(!db)return json({error:"DATABASE_URL is not configured"},503);const sql=neon(db);const u=new URL(req.url),id=u.searchParams.get("id"),action=u.searchParams.get("action");
if(req.method==="GET"){const search=u.searchParams.get("search")?.trim()||"";const rows=search?await sql`select o.*,l.name lead_name,l.email lead_email,c.name company_name from opportunities o join leads l on l.id=o.lead_id left join companies c on c.id=o.company_id where o.name ilike ${"%"+search+"%"} or l.name ilike ${"%"+search+"%"} or l.email ilike ${"%"+search+"%"} or c.name ilike ${"%"+search+"%"} order by o.updated_at desc limit 500`:await sql`select o.*,l.name lead_name,l.email lead_email,c.name company_name from opportunities o join leads l on l.id=o.lead_id left join companies c on c.id=o.company_id order by o.updated_at desc limit 500`;return json({ok:true,opportunities:rows});}
if(req.method==="POST"&&action==="from-lead"){const leadId=u.searchParams.get("leadId");if(!leadId)return json({error:"leadId is required"},400);const leads=await sql`select * from leads where id=${leadId} limit 1`;const l=leads[0];if(!l)return json({error:"Lead not found"},404);const existing=await sql`select id from opportunities where lead_id=${leadId} limit 1`;if(existing[0])return json({ok:true,opportunityId:existing[0].id});const contacts=await sql`select id from contacts where lower(email)=lower(${l.email}) limit 1`;const companies=await sql`select id from companies where lower(name)=lower(${l.company||""}) limit 1`;const now=Date.now();const oid=crypto.randomUUID();const stage=l.status==="won"||l.status==="lost"?l.status:l.status;const probability=stage==="qualified"?60:stage==="contacted"?30:10;await sql`insert into opportunities(id,lead_id,contact_id,company_id,name,stage,value,probability,owner,notes,created_at,updated_at) values(${oid},${leadId},${contacts[0]?.id||null},${companies[0]?.id||null},${l.request||"New opportunity"},${stage},0,${probability},${"Jabari Tech"},${"Created from captured lead."},${now},${now})`;return json({ok:true,opportunityId:oid},201);}
if(req.method==="PUT"){if(!id)return json({error:"id is required"},400);const x=await req.json() as Record<string,unknown>;const stage=String(x.stage||"");const allowed=["new","contacted","qualified","proposal","negotiation","won","lost"];if(!allowed.includes(stage))return json({error:"Invalid stage"},400);const value=Number(x.value);const probability=Number(x.probability);if(!Number.isFinite(value)||value<0||!Number.isFinite(probability)||probability<0||probability>100)return json({error:"Invalid value or probability"},400);const now=Date.now();const old=await sql`select * from opportunities where id=${id} limit 1`;if(!old[0])return json({error:"Opportunity not found"},404);const rows=await sql`update opportunities set stage=${stage},value=${value},probability=${probability},expected_close_at=${x.expectedCloseAt?Number(x.expectedCloseAt):null},notes=${String(x.notes||"")},updated_at=${now} where id=${id} returning *`;if(old[0].stage!==stage){await sql`insert into crm_activities(id,lead_id,type,title,detail,created_at) values(${crypto.randomUUID()},${old[0].lead_id},"status_changed","Opportunity stage changed",${stage},${now})`;if(stage==="won"||stage==="lost"){await sql`update leads set status=${stage},updated_at=${now} where id=${old[0].lead_id}`;await fireTrigger(sql,"stage_changed",old[0].lead_id,stage).catch((e)=>console.error("Workflow trigger error",e));await processDue(sql).catch((e)=>console.error("Workflow process error",e));}}return json({ok:true,opportunity:rows[0]});}
return json({error:"Unsupported opportunities operation"},405);}catch(e){if(e instanceof Response)return e;console.error(e);return json({error:e instanceof Error?e.message:"Opportunity request failed"},500)}};export const config:Config={path:"/api/opportunities"};