import type { Context } from "@netlify/functions";
import { createRemoteJWKSet, jwtVerify } from "jose";
import { neon } from "@neondatabase/serverless";
import { buildBrandedEmailHtml } from "./lib/email-brand";
import { requireOwner, authConfig } from "./lib/auth";
async function sendGmail(to:string,subject:string,bodyText:string){
 const clientId=Netlify.env.get("GOOGLE_CLIENT_ID"),clientSecret=Netlify.env.get("GOOGLE_CLIENT_SECRET"),refreshToken=Netlify.env.get("GMAIL_REFRESH_TOKEN");
 if(!clientId||!clientSecret||!refreshToken)throw new Error("Gmail integration credentials are not configured.");
 const tokenResponse=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:clientId,client_secret:clientSecret,refresh_token:refreshToken,grant_type:"refresh_token"})});
 const token=await tokenResponse.json() as any;if(!tokenResponse.ok||!token.access_token)throw new Error("Google OAuth token refresh failed.");
 const html=buildBrandedEmailHtml({subject,bodyText});const boundary=`----=_Jabari_${crypto.randomUUID().replace(/-/g,"")}`;const clean=(v:string)=>v.replace(/[\r\n]/g," ");const mime=[`From: Jabari <${clean(authConfig().ownerEmail)}>`,`To: ${clean(to)}`,`Subject: ${clean(subject)}`,"MIME-Version: 1.0",`Content-Type: multipart/alternative; boundary="${boundary}"`,"",`--${boundary}`,"Content-Type: text/plain; charset=\"UTF-8\"","",bodyText,"",`--${boundary}`,"Content-Type: text/html; charset=\"UTF-8\"","",html,"",`--${boundary}--`,""].join("\r\n");
 const bytes=new TextEncoder().encode(mime);let binary="";for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,Math.min(i+0x8000,bytes.length)));const raw=btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");
 const r=await fetch("https://gmail.googleapis.com/gmail/v1/users/me/messages/send",{method:"POST",headers:{Authorization:`Bearer ${token.access_token}`,"content-type":"application/json"},body:JSON.stringify({raw})});if(!r.ok)throw new Error("Gmail rejected the send request.");
}
function db(){const u=Netlify.env.get("DATABASE_URL");if(!u)throw new Error("DATABASE_URL is not configured.");return neon(u)}
export default async(req:Request,_context:Context)=>{try{await requireOwner(req);const u=new URL(req.url),action=u.searchParams.get("action")||"list",sql=db();
if(req.method==="GET"&&action==="list"){const rows=await sql`SELECT *,id AS "_id",target_service AS "targetService",target_niche AS "targetNiche",target_location AS "targetLocation",target_condition AS "targetCondition",avoid_terms AS "avoidTerms",qualification_status AS "qualificationStatus",qualification_reason AS "qualificationReason",website_status AS "websiteStatus",contact_email AS "contactEmail",contact_phone AS "contactPhone",contact_name AS "contactName",fit_reason AS "fitReason",pain_point AS "painPoint",outreach_subject AS "outreachSubject",outreach_body AS "outreachBody",analysis_status AS "analysisStatus",contact_status AS "contactStatus",contact_source AS "contactSource",contact_evidence AS "contactEvidence",contact_checked_at AS "contactCheckedAt",website_evidence AS "websiteEvidence",website_found AS "websiteFound",created_at AS "createdAt",updated_at AS "updatedAt" FROM prospects ORDER BY updated_at DESC LIMIT 50`;return Response.json({prospects:rows})}
if(req.method==="GET"&&action==="drafts"){const rows=await sql`SELECT *,id AS "_id",prospect_id AS "prospectId",recipient_email AS "recipientEmail",body_text AS "bodyText",approved_at AS "approvedAt",scheduled_send_at AS "scheduledSendAt",delivery_status AS "deliveryStatus",delivery_error AS "deliveryError",last_delivery_check_at AS "lastDeliveryCheckAt",sent_at AS "sentAt",created_at AS "createdAt",updated_at AS "updatedAt" FROM prospect_outreach_drafts ORDER BY updated_at DESC LIMIT 100`;return Response.json({drafts:rows})}
if(req.method==="PATCH"&&action==="status"){const b=await req.json() as any;if(!b.prospectId||!["research","saved","discarded"].includes(b.status))throw new Error("Invalid prospect status.");await sql`UPDATE prospects SET status=${b.status},updated_at=${Date.now()} WHERE id=${b.prospectId}`;return Response.json({ok:true})}
if(req.method==="DELETE"&&action==="prospect"){const id=u.searchParams.get("id");if(!id)throw new Error("Prospect id is required.");await sql`DELETE FROM prospect_outreach_drafts WHERE prospect_id=${id}`;await sql`DELETE FROM outreach_events WHERE prospect_id=${id}`;await sql`DELETE FROM prospects WHERE id=${id}`;return Response.json({deleted:1})}
if(req.method==="POST"&&action==="draft"){const b=await req.json() as any;const p=(await sql`SELECT id,name,contact_email AS email,contact_status AS "contactStatus",outreach_subject AS "outreachSubject",outreach_body AS "outreachBody" FROM prospects WHERE id=${b.prospectId} LIMIT 1`)[0];if(!p)throw new Error("Prospect not found.");const email=String(p.email||"").trim().toLowerCase();if(!email.includes("@")||p.contactStatus!=="verified")throw new Error("A publicly verified contact email is required before creating outreach.");const existing=await sql`SELECT *,id AS "_id",prospect_id AS "prospectId",recipient_email AS "recipientEmail",body_text AS "bodyText" FROM prospect_outreach_drafts WHERE prospect_id=${b.prospectId} AND status NOT IN ('sent','cancelled') ORDER BY updated_at DESC LIMIT 1`;if(existing[0])return Response.json({draft:existing[0]});const now=Date.now();const rows=await sql`INSERT INTO prospect_outreach_drafts(prospect_id,recipient_email,subject,body_text,status,created_at,updated_at) VALUES(${b.prospectId},${email},${String(p.outreachSubject||"A quick idea for "+p.name)},${String(p.outreachBody||"I noticed your business while researching your space and wanted to share a quick idea.")},'draft',${now},${now}) RETURNING *,id AS "_id",prospect_id AS "prospectId",recipient_email AS "recipientEmail",body_text AS "bodyText"`;return Response.json({draft:rows[0]})}
if(req.method==="PATCH"&&action==="draft"){const b=await req.json() as any;await sql`UPDATE prospect_outreach_drafts SET subject=${String(b.subject||"").trim()},body_text=${String(b.bodyText||"").trim()},status='draft',updated_at=${Date.now()} WHERE id=${b.draftId} AND status NOT IN ('sent','cancelled')`;return Response.json({ok:true})}
if(req.method==="POST"&&action==="approve-draft"){const b=await req.json() as any;const now=Date.now();const pending=await sql`SELECT COALESCE(MAX(scheduled_send_at),0) AS max_scheduled FROM prospect_outreach_drafts WHERE status='approved'`;const scheduled=Math.max(now+3600000,Number(pending[0]?.max_scheduled||0)+3600000);const rows=await sql`UPDATE prospect_outreach_drafts SET status='approved',approved_at=${now},scheduled_send_at=${scheduled},updated_at=${now} WHERE id=${b.draftId} AND status='draft' RETURNING *`;if(!rows[0])throw new Error("Only draft outreach can be approved.");return Response.json({ok:true,scheduledSendAt:scheduled})}
if(req.method==="POST"&&action==="send-draft"){const b=await req.json() as any;const rows=await sql`SELECT * FROM prospect_outreach_drafts WHERE id=${b.draftId} LIMIT 1`;const d=rows[0];if(!d||d.status!=="approved")throw new Error("Only approved drafts can be sent.");try{await sendGmail(String(d.recipient_email),String(d.subject),String(d.body_text))}catch(e){const msg=e instanceof Error?e.message:String(e);await sql`UPDATE prospect_outreach_drafts SET delivery_status='undeliverable',delivery_error=${msg},updated_at=${Date.now()} WHERE id=${d.id}`;throw e}const now=Date.now();await sql`UPDATE prospect_outreach_drafts SET status='sent',sent_at=${now},delivery_status='sent',updated_at=${now} WHERE id=${d.id}`;await sql`INSERT INTO outreach_events(id,kind,prospect_id,metadata,created_at) VALUES(${crypto.randomUUID()},'email_sent',${d.prospect_id},${JSON.stringify({draftId:d.id})},${now})`;return Response.json({ok:true})}
if(req.method==="POST"&&action==="delivery"){const b=await req.json() as any;const rows=await sql`SELECT delivery_status,delivery_error FROM prospect_outreach_drafts WHERE id=${b.draftId} LIMIT 1`;if(!rows[0])throw new Error("Draft not found.");const status=String(rows[0].delivery_status||"unknown");await sql`UPDATE prospect_outreach_drafts SET last_delivery_check_at=${Date.now()},updated_at=${Date.now()} WHERE id=${b.draftId}`;return Response.json({status,error:rows[0].delivery_error||undefined})}
if(req.method==="POST"&&action==="clear-research"){const rows=await sql`DELETE FROM prospects WHERE status='research' RETURNING id`;return Response.json({deleted:rows.length})}
if(req.method==="POST"&&action==="clear-history"){const rows=await sql`DELETE FROM prospects WHERE status NOT IN ('saved') RETURNING id`;for(const r of rows){await sql`DELETE FROM prospect_outreach_drafts WHERE prospect_id=${r.id}`;await sql`DELETE FROM outreach_events WHERE prospect_id=${r.id}`}return Response.json({deleted:rows.length,protected:0})}
return Response.json({error:"Unsupported prospect action."},{status:400})}catch(e){if(e instanceof Response)return e;const m=e instanceof Error?e.message:"Prospect request failed.";return Response.json({error:m},{status:400})}};
