[build]
  command = "npx convex deploy --cmd 'npm run build' --cmd-url-env-var-name VITE_CONVEX_URL"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NITRO_PRESET = "netlify"
  NODE_VERSION = "22"
