import { createFileRoute } from "@tanstack/react-router";
import { useEffect,useState } from "react";
export const Route=createFileRoute("/book/$bookingTypeId")({component:PublicBooking});
function PublicBooking(){
 const {bookingTypeId}=Route.useParams(); const source=new URLSearchParams(window.location.search).get("source")||"booking_page";
 const [type,setType]=useState<any>(undefined),[day,setDay]=useState(()=>{const d=new Date();d.setHours(0,0,0,0);return d}),[slot,setSlot]=useState<number|null>(null),[slots,setSlots]=useState<number[]>([]),[form,setForm]=useState({name:"",email:"",phone:"",company:"",notes:""}),[done,setDone]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{void fetch("/api/bookings?action=public&bookingTypeId="+encodeURIComponent(bookingTypeId)).then(r=>r.json()).then(x=>setType(x.type||null)).catch(()=>setType(null))},[bookingTypeId]);
 useEffect(()=>{if(!type)return;setSlot(null);void fetch("/api/bookings?action=available&bookingTypeId="+encodeURIComponent(bookingTypeId)+"&from="+day.getTime()+"&to="+(day.getTime()+86400000)).then(r=>r.json()).then(x=>setSlots(x.slots||[])).catch(()=>setSlots([]))},[type,bookingTypeId,day]);
 if(type===undefined)return <main className="grid min-h-screen place-items-center bg-[#080808] text-white/40">Loading booking page…</main>;
 if(!type)return <main className="grid min-h-screen place-items-center bg-[#080808] text-white/40">This booking page is unavailable.</main>;
 if(done)return <main className="grid min-h-screen place-items-center bg-[#080808] px-5 text-center text-white"><div><p className="text-xs uppercase tracking-[.2em] text-[#d4af37]">Booking confirmed</p><h1 className="mt-3 text-3xl font-bold">You're booked.</h1><p className="mt-2 text-white/45">{slot?new Date(slot).toLocaleString():""} · {type.name}</p></div></main>;
 return <main className="min-h-screen bg-[#080808] px-5 py-12 text-white"><div className="mx-auto max-w-2xl"><p className="text-xs uppercase tracking-[.2em] text-[#d4af37]">Jabari Assistant</p><h1 className="mt-2 text-3xl font-bold">{type.name}</h1><p className="mt-2 text-sm text-white/45">{type.description} · {type.durationMinutes} minutes · {type.timezone}</p><div className="mt-8 grid gap-6 md:grid-cols-[.8fr_1.2fr]"><div><label className="text-xs text-white/50">Choose a day</label><input type="date" value={day.toISOString().slice(0,10)} onChange={e=>{const d=new Date(e.target.value+"T00:00");setDay(d)}} className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.04] p-3 text-sm"/></div><div><label className="text-xs text-white/50">Available times</label><div className="mt-2 grid grid-cols-2 gap-2">{slots.map(t=><button key={t} onClick={()=>setSlot(t)} className={"rounded-xl border p-3 text-xs "+(slot===t?"border-[#d4af37] bg-[#d4af37]/10 text-[#d4af37]":"border-white/10 text-white/60")}>{new Date(t).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}</button>)}{slots.length===0&&<p className="col-span-2 text-xs text-white/30">No open times for this day.</p>}</div></div></div>{slot&&<form className="mt-8 grid gap-3 md:grid-cols-2" onSubmit={async e=>{e.preventDefault();setError("");setBusy(true);try{const r=await fetch("/api/bookings?action=book&bookingTypeId="+encodeURIComponent(bookingTypeId),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,startAt:slot,honeypot:"",source})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Unable to complete booking.");setDone(true)}catch(err){setError(err instanceof Error?err.message:"Unable to complete booking.")}finally{setBusy(false)}}}>{(["name","email","phone","company"] as const).map(k=><input key={k} required={k==="name"||k==="email"} type={k==="email"?"email":"text"} placeholder={k[0].toUpperCase()+k.slice(1)} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="rounded-xl border border-white/10 bg-white/[.04] p-3 text-sm"/>)}<textarea placeholder="Anything we should know? (optional)" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className="md:col-span-2 rounded-xl border border-white/10 bg-white/[.04] p-3 text-sm"/>{error&&<p className="md:col-span-2 rounded-lg border border-red-500/20 p-3 text-xs text-red-300">{error}</p>}<button disabled={busy} className="md:col-span-2 rounded-xl bg-[#d4af37] p-3 text-sm font-bold text-black disabled:opacity-50">{busy?"Confirming…":"Confirm booking"}</button></form>}</div></main>
}