import { useMemo, useState } from "react"
import { useConvexAuth, useMutation, useQuery } from "convex/react"
import { api } from "../../convex/_generated/api"
import type { Id } from "../../convex/_generated/dataModel"

function dayKey(ts:number){return new Date(ts).toISOString().slice(0,10)}
function fmt(ts:number){return new Date(ts).toLocaleString([], {month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}

export function AppointmentsCalendar(){
 const {isAuthenticated}=useConvexAuth()
 const [cursor,setCursor]=useState(()=>{const d=new Date();d.setHours(0,0,0,0);return d.getTime()})
 const [open,setOpen]=useState(false),[error,setError]=useState("")
 const [form,setForm]=useState({title:"",description:"",date:"",start:"09:00",end:"10:00",location:"Online",meetingUrl:""})
 const from=cursor,to=cursor+7*86400000
 const rows=useQuery(api.appointments.list,isAuthenticated?{from,to}:"skip")||[]
 const create=useMutation(api.appointments.create), updateStatus=useMutation(api.appointments.updateStatus)
 const days=useMemo(()=>Array.from({length:7},(_,i)=>new Date(cursor+i*86400000)),[cursor])
 async function submit(){if(!form.title||!form.date)return;const start=new Date(form.date+"T"+form.start).getTime(),end=new Date(form.date+"T"+form.end).getTime();try{await create({title:form.title,description:form.description,startAt:start,endAt:end,location:form.location,meetingUrl:form.meetingUrl||undefined});setOpen(false);setForm({title:"",description:"",date:"",start:"09:00",end:"10:00",location:"Online",meetingUrl:""})}catch(e){setError(e instanceof Error?e.message:"Unable to create appointment")}}
 async function status(id:Id<"appointments">,s:"scheduled"|"confirmed"|"completed"|"cancelled"){try{await updateStatus({appointmentId:id,status:s})}catch(e){setError(e instanceof Error?e.message:"Unable to update appointment")}}
 return <section className="rounded-3xl border border-white/10 bg-black/30 p-5" id="appointments"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[11px] font-semibold uppercase tracking-[.22em] text-[#d8b45a]">Appointments</div><h2 className="mt-1 text-xl font-semibold text-white">Calendar</h2><p className="mt-1 text-sm text-white/50">Schedule discovery calls, client meetings and follow-ups.</p></div><div className="flex gap-2"><button className="rounded-xl border border-white/10 px-3 py-2 text-xs text-white/70" onClick={()=>setCursor(cursor-7*86400000)}>←</button><button className="rounded-xl border border-white/10 px-3 py-2 text-xs text-white/70" onClick={()=>{const d=new Date();d.setHours(0,0,0,0);setCursor(d.getTime())}}>Today</button><button className="rounded-xl border border-white/10 px-3 py-2 text-xs text-white/70" onClick={()=>setCursor(cursor+7*86400000)}>→</button><button className="rounded-xl bg-[#d8b45a] px-3 py-2 text-xs font-semibold text-black" onClick={()=>{setOpen(true);setForm({...form,date:new Date(cursor).toISOString().slice(0,10)})}}>+ Appointment</button></div></div>
 {error&&<div className="mt-4 rounded-xl border border-red-400/20 bg-red-400/5 px-3 py-2 text-xs text-red-200">{error}</div>}
 <div className="mt-5 grid gap-2 md:grid-cols-7">{days.map(day=>{const key=dayKey(day.getTime()),items=rows.filter((r:any)=>dayKey(Number(r.startAt))===key);return <div key={key} className="min-h-32 rounded-2xl border border-white/10 bg-white/[.025] p-3"><div className="text-xs font-semibold text-white">{day.toLocaleDateString([], {weekday:"short"})}</div><div className="text-[11px] text-white/40">{day.toLocaleDateString([], {month:"short",day:"numeric"})}</div><div className="mt-3 space-y-2">{items.map((r:any)=><div key={r._id} className="rounded-xl border border-[#d8b45a]/20 bg-[#d8b45a]/5 p-2"><div className="text-xs font-medium text-white">{r.title}</div><div className="mt-1 text-[10px] text-white/50">{fmt(Number(r.startAt))}</div><div className="mt-1 text-[10px] uppercase text-[#d8b45a]">{r.status}</div>{r.status!=="completed"&&r.status!=="cancelled"&&<div className="mt-2 flex flex-wrap gap-1">{r.status==="scheduled"&&<button className="rounded-md border border-white/10 px-2 py-1 text-[9px] text-white/60" onClick={()=>void status(r._id,"confirmed")}>Confirm</button>}<button className="rounded-md border border-white/10 px-2 py-1 text-[9px] text-white/60" onClick={()=>void status(r._id,"completed")}>Complete</button><button className="rounded-md border border-red-400/20 px-2 py-1 text-[9px] text-red-200/70" onClick={()=>void status(r._id,"cancelled")}>Cancel</button></div>}</div>)}</div></div>})}</div>
 {open&&<div className="mt-5 rounded-2xl border border-white/10 bg-white/[.03] p-4"><div className="grid gap-3 md:grid-cols-2">{[["title","Appointment title"],["date","Date"],["start","Start"],["end","End"],["location","Location"],["meetingUrl","Meeting URL"]].map(([k,p])=><input key={k} className="rounded-xl border border-white/10 bg-black/30 p-3 text-sm text-white" placeholder={p} type={k==="date"?"date":k==="start"||k==="end"?"time":"text"} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}<textarea className="rounded-xl border border-white/10 bg-black/30 p-3 text-sm text-white md:col-span-2" placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="mt-3 flex gap-2"><button className="rounded-xl bg-[#d8b45a] px-4 py-2 text-sm font-semibold text-black" onClick={()=>void submit()}>Save appointment</button><button className="rounded-xl border border-white/10 px-4 py-2 text-sm text-white/60" onClick={()=>setOpen(false)}>Cancel</button></div></div>}</section>
}
