import { useState } from "react";
import { neonApi, neonFetch } from "../lib/neon-api";
export function BookingManager(){
 const [types,setTypes]=useState<any[]>([]),[name,setName]=useState(""),[duration,setDuration]=useState("30"),[selected,setSelected]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(){const r=await neonApi<any>("bookings");setTypes(r.types||[]);if(selected){const fresh=(r.types||[]).find((x:any)=>x.id===selected.id);if(fresh)setSelected(fresh)}}
 async function add(){if(!name.trim())return;setBusy(true);setError("");try{await neonFetch("/api/bookings?action=create",{method:"POST",body:JSON.stringify({name,description:"Schedule a conversation with our team.",durationMinutes:Number(duration),location:"Online",timezone:Intl.DateTimeFormat().resolvedOptions().timeZone})});setName("");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to create booking type.")}finally{setBusy(false)}}
 async function status(){if(!selected)return;await neonFetch("/api/bookings?action=status",{method:"POST",body:JSON.stringify({bookingTypeId:selected.id,status:selected.status==="published"?"paused":"published"})});await load()}
 return <section id="booking" className="mt-8 overflow-hidden rounded-2xl border border-white/10 bg-white/[.03]">
  <div className="border-b border-white/10 p-5"><p className="text-xs uppercase tracking-[.18em] text-[#d4af37]">Booking & Scheduling</p><h2 className="mt-1 text-xl font-bold">Booking pages</h2><p className="mt-1 text-xs text-white/40">Publish appointment types with availability, conflict protection and CRM capture.</p></div>
  <div className="grid gap-3 border-b border-white/10 p-5 md:grid-cols-[1fr_140px_auto]"><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Discovery Call" className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs"/><input value={duration} onChange={e=>setDuration(e.target.value)} type="number" min="15" step="15" className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs"/><button disabled={!name.trim()||busy} onClick={()=>void add()} className="rounded-lg bg-[#d4af37] px-4 py-2 text-xs font-bold text-black disabled:opacity-40">Create booking type</button></div>
  {error&&<p className="mx-5 mt-4 rounded-lg border border-red-500/20 p-3 text-xs text-red-300">{error}</p>}
  <div className="grid gap-4 p-5 lg:grid-cols-[1fr_1.5fr]"><div className="space-y-2">{types.length===0?<p className="text-sm text-white/30">No booking types yet.</p>:types.map(t=><button key={t.id} onClick={()=>setSelected(t)} className={"w-full rounded-xl border p-4 text-left "+(selected?.id===t.id?"border-[#d4af37]/40 bg-[#d4af37]/5":"border-white/10")}><div className="flex justify-between"><span className="font-semibold">{t.name}</span><span className="text-[10px] uppercase text-white/35">{t.status}</span></div><p className="mt-1 text-xs text-white/35">{t.durationMinutes} minutes · {t.timezone}</p></button>)}</div>
   {selected?<div className="rounded-xl border border-white/10 p-4"><h3 className="font-semibold">{selected.name}</h3><p className="mt-1 text-xs text-white/40">{selected.description}</p><div className="mt-5 rounded-xl bg-black/20 p-4 text-xs text-white/45">Availability: weekdays, 9:00 AM–5:00 PM in {selected.timezone}. Slots are checked live and blocked automatically when booked.</div><div className="mt-4 flex gap-2"><button onClick={()=>void status()} className="rounded-lg border border-[#d4af37]/30 px-3 py-2 text-xs text-[#d4af37]">{selected.status==="published"?"Pause booking page":"Publish booking page"}</button><span className="rounded-lg border border-white/10 px-3 py-2 text-[10px] text-white/30">/book/{selected.id}</span></div></div>:<div className="grid min-h-40 place-items-center rounded-xl border border-dashed border-white/10 text-sm text-white/30">Select a booking type to manage it.</div>}
  </div>
 </section>
}