import { useEffect, useState } from "react"
import { useConvexAuth, useMutation, useQuery } from "convex/react"
import { api } from "../../convex/_generated/api"

type Step={type:"email"|"create_task"|"add_note"|"update_stage";delayMinutes:number;subject:string;body:string}
const labels={email:"Send email",create_task:"Create task",add_note:"Add CRM note",update_stage:"Move lead stage"} as const

export function CampaignsSequences(){
 const {isAuthenticated,isLoading}=useConvexAuth()
 const campaigns=useQuery(api.campaigns.list,isAuthenticated?{}:"skip")||[]
 const [selectedId,setSelectedId]=useState<any>(null),[name,setName]=useState(""),[description,setDescription]=useState("")
 const [steps,setSteps]=useState<Step[]>([{type:"email",delayMinutes:0,subject:"Following up from Jabari Tech",body:"Hi {{name}},\n\nI wanted to follow up and see if you have any questions.\n\nBest,\nJabari Tech"}])
 const [busy,setBusy]=useState(false),[error,setError]=useState("")
 const selected=campaigns.find((c:any)=>String(c._id)===String(selectedId))||null
 const leads=useQuery(api.campaigns.leadsForEnrollment,selected?{campaignId:selected._id}:"skip")||[]
 const events=useQuery(api.campaigns.recentEvents,selected?{campaignId:selected._id}:"skip")||[]
 const create=useMutation(api.campaigns.create),setStatus=useMutation(api.campaigns.setStatus),enroll=useMutation(api.campaigns.enroll)
 useEffect(()=>{if(selectedId&&!selected)setSelectedId(null)},[selectedId,selected])
 const update=(i:number,p:Partial<Step>)=>setSteps(s=>s.map((x,n)=>n===i?{...x,...p}:x))
 const add=async()=>{if(!name.trim()||steps.some(s=>!s.body.trim()))return;setBusy(true);setError("");try{await create({name,description,steps});setName("");setDescription("")}catch(e){setError(e instanceof Error?e.message:"Unable to create campaign")}finally{setBusy(false)}}
 if(isLoading||!isAuthenticated)return <section className="rounded-2xl border border-white/10 bg-white/[0.03] p-5 text-sm text-white/40">Checking authentication…</section>
 return <section id="campaigns" className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]">
  <div className="border-b border-white/10 p-5"><p className="text-xs uppercase tracking-[.18em] text-[#d4af37]">Campaigns & Sequences</p><h2 className="mt-1 text-xl font-bold">Reusable outreach journeys</h2><p className="mt-1 text-xs text-white/40">Build a sequence once, activate it, then enroll leads.</p>{error&&<p className="mt-2 text-xs text-red-300">{error}</p>}</div>
  <div className="grid gap-4 border-b border-white/10 p-5 md:grid-cols-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Campaign name" className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs"/><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description (optional)" className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs"/></div>
  <div className="space-y-3 px-5 pb-5">{steps.map((s,i)=><div key={i} className="rounded-xl border border-white/10 bg-black/20 p-4"><div className="mb-3 flex items-center justify-between"><span className="text-[10px] uppercase tracking-wider text-white/35">Step {i+1}</span>{steps.length>1&&<button onClick={()=>setSteps(x=>x.filter((_,n)=>n!==i))} className="text-[10px] text-red-300">Remove</button>}</div><div className="grid gap-2 md:grid-cols-[180px_110px_1fr]"><select value={s.type} onChange={e=>update(i,{type:e.target.value as Step["type"]})} className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs">{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input type="number" min="0" value={s.delayMinutes} onChange={e=>update(i,{delayMinutes:Number(e.target.value)||0})} className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs" placeholder="Delay min"/>{s.type==="email"&&<input value={s.subject} onChange={e=>update(i,{subject:e.target.value})} placeholder="Email subject" className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs"/>}</div><textarea value={s.body} onChange={e=>update(i,{body:e.target.value})} rows={4} className="mt-2 w-full resize-y rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs" placeholder="Step instruction or email body"/></div>)}<div className="flex flex-wrap gap-2"><button onClick={()=>setSteps(s=>[...s,{type:"email",delayMinutes:1440,subject:"A quick follow-up",body:"Hi {{name}},\n\nJust checking in on my previous message.\n\nBest,\nJabari Tech"}])} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-white/55">+ Add step</button><button disabled={busy} onClick={()=>void add()} className="rounded-lg bg-[#d4af37] px-4 py-2 text-xs font-bold text-black disabled:opacity-50">{busy?"Creating…":"Create campaign"}</button></div></div>
  <div className="grid gap-4 border-t border-white/10 p-5 lg:grid-cols-[1fr_1.4fr]">
   <div className="space-y-2">{campaigns.length===0?<p className="text-sm text-white/35">No campaigns yet.</p>:campaigns.map((c:any)=><button key={String(c._id)} onClick={()=>setSelectedId(c._id)} className={"w-full rounded-xl border p-4 text-left transition "+(selectedId===c._id?"border-[#d4af37]/40 bg-[#d4af37]/5":"border-white/10 bg-black/10 hover:bg-white/[.03]")}><div className="flex items-center justify-between gap-2"><span className="font-semibold">{c.name}</span><span className="rounded-full bg-white/10 px-2 py-1 text-[10px] capitalize text-white/50">{c.status}</span></div><p className="mt-1 text-xs text-white/35">{c.steps.length} steps · {c.activeEnrollments} active enrollments</p></button>)}</div>
   {selected?<div className="rounded-xl border border-white/10 bg-black/10 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{selected.name}</h3><p className="mt-1 text-xs text-white/40">{selected.description||"No description"}</p></div><button onClick={()=>void setStatus({campaignId:selected._id,status:selected.status==="active"?"paused":"active"}).catch(e=>setError(e instanceof Error?e.message:"Unable to update campaign"))} className="rounded-lg border border-[#d4af37]/30 px-3 py-2 text-xs text-[#d4af37]">{selected.status==="active"?"Pause":"Activate"}</button></div>
    <div className="mt-4 rounded-lg border border-white/10 p-3"><p className="text-[10px] uppercase tracking-wider text-white/35">Sequence</p>{selected.steps.map((s:any)=><div key={String(s._id)} className="mt-2 flex justify-between gap-3 text-xs"><span>{s.order+1}. {labels[s.type as keyof typeof labels]}</span><span className="text-white/35">{s.delayMinutes===0?"Immediately":s.delayMinutes+" min delay"}</span></div>)}</div>
    <div className="mt-4"><p className="text-[10px] uppercase tracking-wider text-white/35">Enroll leads</p><div className="mt-2 max-h-56 space-y-1 overflow-auto">{leads.map((l:any)=><div key={String(l._id)} className="flex items-center justify-between gap-3 rounded-lg border border-white/5 px-3 py-2"><div><p className="text-xs font-medium">{l.name}</p><p className="text-[10px] text-white/35">{l.email} · {l.status}</p></div><button disabled={l.enrolled||selected.status!=="active"} onClick={()=>void enroll({campaignId:selected._id,leadId:l._id}).catch(e=>setError(e instanceof Error?e.message:"Unable to enroll lead"))} className="rounded-lg border border-white/10 px-2 py-1 text-[10px] text-white/55 disabled:opacity-30">{l.enrolled?"Enrolled":"Enroll"}</button></div>)}</div></div>
    <div className="mt-4"><p className="text-[10px] uppercase tracking-wider text-white/35">Recent execution</p>{events.slice(0,8).map((e:any)=><div key={String(e._id)} className="mt-2 flex justify-between gap-3 text-[10px]"><span className="text-white/55">{e.detail}</span><span className="text-white/25">{new Date(Number(e.createdAt)).toLocaleString()}</span></div>)}</div>
   </div>:<div className="grid min-h-48 place-items-center rounded-xl border border-dashed border-white/10 text-sm text-white/30">Select a campaign to manage its sequence.</div>}
  </div>
 </section>
}
