import { useState } from "react"
import { useConvexAuth, useMutation, useQuery } from "convex/react"
import { api } from "../../convex/_generated/api"
import type { Id } from "../../convex/_generated/dataModel"

const icon=(kind:string)=>kind==="email_received"||kind==="outreach"?"✉":kind==="task"?"✓":kind==="appointment"?"◷":kind==="billing"?"$":"•"
const when=(v:number)=>new Date(v).toLocaleString([], {dateStyle:"medium",timeStyle:"short"})

export function ContactsCrm(){
 const {isAuthenticated}=useConvexAuth()
 const [search,setSearch]=useState(""),[selected,setSelected]=useState<Id<"contacts">|null>(null),[note,setNote]=useState(""),[editing,setEditing]=useState(false),[form,setForm]=useState<Record<string,string>>({}),[message,setMessage]=useState("")
 const rows=useQuery(api.contacts.list,isAuthenticated?{search:search||undefined}:"skip"),detail=useQuery(api.contacts.get,selected?{contactId:selected}:"skip"),activities=useQuery(api.contacts.listActivities,selected?{contactId:selected}:"skip")
 const update=useMutation(api.contacts.update),addNote=useMutation(api.contacts.addNote),contacts=rows??[]
 const open=(c:any)=>{setSelected(c._id);setEditing(false);setForm({name:c.name,email:c.email,company:c.company,phone:c.phone||"",jobTitle:c.jobTitle||"",website:c.website||"",notes:c.notes||"",tags:(c.tags||[]).join(", ")})}
 const save=async()=>{if(!selected)return;await update({contactId:selected,name:form.name||"",email:form.email||"",company:form.company||"",phone:form.phone||undefined,jobTitle:form.jobTitle||undefined,website:form.website||undefined,notes:form.notes||undefined,tags:String(form.tags||"").split(",").map(x=>x.trim()).filter(Boolean)});setEditing(false);setMessage("Contact updated.")}
 const add=async()=>{if(!selected||!note.trim())return;await addNote({contactId:selected,detail:note.trim()});setNote("");setMessage("Note added.")}
 const exportCsv=()=>{const out=[[ "name","email","company","phone","jobTitle","website","notes","tags"],...contacts.map((c:any)=>[c.name,c.email,c.company,c.phone||"",c.jobTitle||"",c.website||"",c.notes||"",(c.tags||[]).join("|")])].map(r=>r.map(v=>{const s=String(v);return /[",\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}).join(",")).join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([out],{type:"text/csv"}));a.download="jabari-contacts.csv";a.click();URL.revokeObjectURL(a.href)}
 return <section className="mt-8 scroll-mt-24 overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]">
  <div className="border-b border-white/10 p-5"><p className="text-xs uppercase tracking-[0.18em] text-[#d4af37]">CRM / Contacts</p><div className="mt-1 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Contacts</h2><p className="mt-1 text-sm text-white/40">People, roles, company context and unified CRM activity.</p></div><div className="flex gap-2"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search contacts..." className="w-52 rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs text-white outline-none"/><button onClick={exportCsv} disabled={!contacts.length} className="rounded-lg bg-[#d4af37] px-3 py-2 text-xs font-semibold text-black disabled:opacity-40">Export CSV</button></div></div>{message&&<p className="mt-3 text-xs text-green-300">{message}</p>}</div>
  <div className="grid md:grid-cols-[1.05fr_.95fr]">
   <div className="max-h-[620px] overflow-y-auto divide-y divide-white/10">{rows===undefined?<p className="p-5 text-sm text-white/40">Loading contacts…</p>:!contacts.length?<p className="p-5 text-sm text-white/40">No CRM contacts yet.</p>:contacts.map((c:any)=><button key={c._id} onClick={()=>open(c)} className={"block w-full p-4 text-left hover:bg-white/[0.03] "+(selected===c._id?"bg-[#d4af37]/[0.05]":"")}><p className="text-sm font-semibold">{c.name}</p><p className="mt-1 text-xs text-white/45">{c.jobTitle||"Contact"}{c.company?" · "+c.company:""}</p><p className="mt-1 text-xs text-white/35">{c.email}{c.phone?" · "+c.phone:""}</p></button>)}</div>
   <div className="min-h-[500px] border-t border-white/10 p-5 md:border-l md:border-t-0">
    {!selected?<p className="text-sm text-white/35">Select a contact to open the record.</p>:detail===undefined?<p className="text-sm text-white/35">Loading record…</p>:!detail?<p className="text-sm text-red-300">Contact not found.</p>:
    <><div className="flex items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.16em] text-[#d4af37]">Contact record</p><h3 className="mt-1 text-lg font-bold">{detail.contact.name}</h3><p className="text-xs text-white/40">{detail.contact.email}</p></div><button onClick={()=>setEditing(x=>!x)} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-white/60">{editing?"Cancel":"Edit"}</button></div>
     {editing?<div className="mt-4 grid gap-2 sm:grid-cols-2">{["name","email","company","phone","jobTitle","website"].map(k=><input key={k} value={form[k]||""} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={k} className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs text-white"/>)}<input value={form.tags||""} onChange={e=>setForm({...form,tags:e.target.value})} placeholder="tags, comma separated" className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs text-white sm:col-span-2"/><textarea value={form.notes||""} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Contact notes" rows={3} className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs text-white sm:col-span-2"/><button onClick={()=>void save()} className="rounded-lg bg-[#d4af37] px-3 py-2 text-xs font-semibold text-black sm:col-span-2">Save contact</button></div>:<div className="mt-4 space-y-2 text-xs text-white/50"><p><b className="text-white/70">Role:</b> {detail.contact.jobTitle||"Not set"}</p><p><b className="text-white/70">Company:</b> {detail.company?.name||detail.contact.company||"Not set"}</p><p><b className="text-white/70">Website:</b> {detail.contact.website||detail.company?.website||"Not set"}</p><p><b className="text-white/70">Tags:</b> {(detail.contact.tags||[]).join(", ")||"None"}</p>{detail.contact.notes&&<p><b className="text-white/70">Notes:</b> {detail.contact.notes}</p>}</div>}
     <div className="mt-5 border-t border-white/10 pt-4"><div className="flex items-center justify-between"><p className="text-xs uppercase tracking-[0.16em] text-[#d4af37]">Unified timeline</p><span className="text-[10px] text-white/30">{(activities||[]).length} events</span></div><div className="mt-3 max-h-72 space-y-2 overflow-y-auto">{activities===undefined?<p className="text-xs text-white/35">Loading timeline…</p>:!activities.length?<p className="text-xs text-white/35">No activity yet.</p>:activities.map((a:any)=><div key={a._id} className="rounded-xl border border-white/10 bg-black/20 p-3"><div className="flex gap-3"><span className="mt-0.5 text-sm text-[#d4af37]">{icon(a.type||a.kind)}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs font-semibold">{a.title}</p><span className="text-[10px] text-white/30">{when(a.createdAt)}</span></div>{a.detail&&<p className="mt-1 text-xs leading-5 text-white/45">{a.detail}</p>}</div></div></div>)}</div><div className="mt-3 flex gap-2"><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Add a note..." className="flex-1 rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs text-white"/><button onClick={()=>void add()} className="rounded-lg border border-[#d4af37]/30 px-3 py-2 text-xs text-[#d4af37]">Add</button></div></div></>}
   </div>
  </div>
 </section>
}
