import { useEffect, useMemo, useState } from "react"
import { neonFetch } from "../lib/neon-api"

type Lead = { id:string; name:string; email:string; company?:string|null; request:string; status:string; updated_at:number }
type Detail = { lead:Lead; messages:any[]; contact:any; activities:any[] }
type Draft = { id:string; subject:string; body_text:string; status:string; sent_at?:number|null }

export function ConversationsInbox({ onOpenLead }: { onOpenLead: (id:string) => void }) {
 const [leads,setLeads]=useState<Lead[]>([]),[selectedId,setSelectedId]=useState<string|null>(null),[detail,setDetail]=useState<Detail|null>(null)
 const [search,setSearch]=useState(""),[filter,setFilter]=useState("all"),[status,setStatus]=useState(""),[drafts,setDrafts]=useState<Draft[]>([]),[busy,setBusy]=useState(false)
 const load=async()=>{try{const r=await neonFetch<{leads:Lead[]}>("/api/leads?resource=leads");setLeads(r.leads)}catch(e){setStatus(e instanceof Error?e.message:"Could not load inbox.")}}
 useEffect(()=>{void load()},[])
 const rows=useMemo(()=>leads.filter(l=>{const q=search.trim().toLowerCase();return(!q||[l.name,l.email,l.company,l.request].join(" ").toLowerCase().includes(q))&&(filter==="all"||l.status===filter)}),[leads,search,filter])
 useEffect(()=>{if(!selectedId){setDetail(null);setDrafts([]);return}setStatus("");void (async()=>{try{const d=await neonFetch<Detail>("/api/leads?resource=lead&id="+encodeURIComponent(selectedId));setDetail(d);const o=await neonFetch<{drafts:Draft[]}>("/api/outreach?action=list&id="+encodeURIComponent(selectedId));setDrafts(o.drafts)}catch(e){setStatus(e instanceof Error?e.message:"Could not load conversation.")}})()},[selectedId])
 const createDraft=async()=>{if(!selectedId)return;setBusy(true);setStatus("");try{const r=await neonFetch<{draft:Draft}>("/api/outreach?action=create&id="+encodeURIComponent(selectedId),{method:"POST"});setDrafts(x=>[r.draft,...x.filter(d=>d.id!==r.draft.id)]);setStatus("AI follow-up draft created. Review it before sending.")}catch(e){setStatus(e instanceof Error?e.message:"Could not create draft.")}finally{setBusy(false)}}
 const updateDraft=async(d:Draft)=>{setBusy(true);try{const r=await neonFetch<{draft:Draft}>("/api/outreach?action=update&id="+encodeURIComponent(d.id),{method:"PUT",body:JSON.stringify({subject:d.subject,bodyText:d.body_text})});setDrafts(x=>x.map(v=>v.id===d.id?r.draft:v));setStatus("Draft saved.")}catch(e){setStatus(e instanceof Error?e.message:"Could not save draft.")}finally{setBusy(false)}}
 const approve=async(id:string)=>{setBusy(true);try{const r=await neonFetch<{draft:Draft}>("/api/outreach?action=approve&id="+encodeURIComponent(id),{method:"POST"});setDrafts(x=>x.map(d=>d.id===id?r.draft:d));setStatus("Approved. It is ready for Gmail send.")}catch(e){setStatus(e instanceof Error?e.message:"Could not approve draft.")}finally{setBusy(false)}}
 const send=async(id:string)=>{setBusy(true);try{const r=await neonFetch<{draft:Draft}>("/api/outreach?action=send&id="+encodeURIComponent(id),{method:"POST"});setDrafts(x=>x.map(d=>d.id===id?r.draft:d));setStatus("Sent through the connected Gmail account.")}catch(e){setStatus(e instanceof Error?e.message:"Could not send email.")}finally{setBusy(false)}}
 return <section id="conversations" className="mt-8 scroll-mt-24 overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]">
  <div className="border-b border-white/10 p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.18em] text-[#d4af37]">Conversations</p><h2 className="mt-1 text-xl font-bold">Unified Inbox</h2><p className="mt-1 text-xs text-white/40">Neon conversations, CRM context, outreach drafts and Gmail sending in one workspace.</p></div>{detail&&<button onClick={()=>onOpenLead(detail.lead.id)} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-white/60">Open CRM record →</button>}</div>
   <div className="mt-4 flex flex-wrap gap-2"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search leads and conversations..." className="min-w-[220px] flex-1 rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs outline-none"/>{["all","new","contacted","qualified","won","lost"].map(x=><button key={x} onClick={()=>setFilter(x)} className={"rounded-full px-3 py-2 text-[10px] capitalize "+(filter===x?"bg-[#d4af37] text-black":"border border-white/10 text-white/45")}>{x}</button>)}</div>
  </div>
  <div className="grid min-h-[560px] md:grid-cols-[320px_1fr]"><div className="border-r border-white/10">{rows.length===0?<p className="p-5 text-sm text-white/40">No conversations match this view.</p>:rows.map(l=><button key={l.id} onClick={()=>setSelectedId(l.id)} className={"block w-full border-b border-white/10 p-4 text-left "+(selectedId===l.id?"bg-white/[0.06]":"hover:bg-white/[0.025]")}><div className="flex justify-between gap-2"><span className="truncate text-sm font-semibold">{l.name}</span><span className="rounded-full bg-white/10 px-2 py-0.5 text-[9px] capitalize text-white/45">{l.status}</span></div><p className="mt-1 truncate text-[11px] text-white/40">{l.company||l.email}</p><p className="mt-2 line-clamp-2 text-xs text-white/55">{l.request}</p><p className="mt-2 text-[9px] text-white/25">{new Date(l.updated_at).toLocaleString()}</p></button>)}</div>
   <div className="min-w-0 overflow-y-auto">{!detail?<div className="grid h-full place-items-center p-8 text-sm text-white/35">Select a conversation.</div>:<>
    <div className="border-b border-white/10 p-5"><h3 className="text-lg font-bold">{detail.lead.name}</h3><p className="mt-1 text-xs text-white/45">{detail.lead.email}{detail.lead.company?" · "+detail.lead.company:""}</p></div>
    <div className="space-y-3 p-5">{detail.messages.length?detail.messages.map((m:any,i:number)=>{const text=m.message??(m.parts??[]).filter((p:any)=>p.type==="text").map((p:any)=>p.text??"").join("");return text?<article key={m.id||i} className={"max-w-[88%] rounded-2xl border px-4 py-3 text-sm "+(m.role==="user"?"ml-auto border-[#d4af37]/20 bg-[#d4af37]/10":"border-white/10 bg-white/[0.04]")}><p className="mb-1 text-[9px] uppercase tracking-wider text-white/30">{m.role==="user"?"Lead":"Jabari Assistant"}</p><p className="whitespace-pre-wrap text-white/75">{text}</p></article>:null}):<p className="text-sm text-white/35">No messages in this conversation.</p>}</div>
    <div className="border-t border-white/10 p-5"><div className="flex items-center justify-between"><p className="text-xs uppercase tracking-[0.16em] text-[#d4af37]">Outreach</p><button onClick={()=>void createDraft()} disabled={busy} className="rounded-lg bg-[#d4af37] px-3 py-2 text-xs font-semibold text-black">{busy?"Working…":"Create AI follow-up"}</button></div>
      <div className="mt-3 space-y-3">{drafts.map(d=><div key={d.id} className="rounded-xl border border-white/10 bg-black/20 p-4"><div className="grid gap-2"><input value={d.subject} onChange={e=>setDrafts(xs=>xs.map(v=>v.id===d.id?{...v,subject:e.target.value}:v))} disabled={d.status!=="draft"} className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs text-white"/><textarea value={d.body_text} onChange={e=>setDrafts(xs=>xs.map(v=>v.id===d.id?{...v,body_text:e.target.value}:v))} disabled={d.status!=="draft"} rows={5} className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs text-white"/><div className="flex flex-wrap gap-2"><span className="rounded-full border border-white/10 px-2 py-1 text-[9px] capitalize text-white/40">{d.status}</span>{d.status==="draft"&&<><button onClick={()=>void updateDraft(d)} disabled={busy} className="rounded-lg border border-white/10 px-3 py-2 text-[10px] text-white/60">Save</button><button onClick={()=>void approve(d.id)} disabled={busy} className="rounded-lg border border-[#d4af37]/30 px-3 py-2 text-[10px] text-[#d4af37]">Approve</button></>}{d.status==="approved"&&<button onClick={()=>void send(d.id)} disabled={busy} className="rounded-lg bg-[#d4af37] px-3 py-2 text-[10px] font-bold text-black">Send via Gmail</button>}</div></div></div>)}</div>
    </div>
    {status&&<div className="border-t border-white/10 p-4 text-xs text-white/45">{status}</div>}
   </>}
  </div></div>
 </section>
}