import { useEffect, useState } from "react";
import { neonFetch } from "../lib/neon-api";
type Draft={id:string;subject:string;body_text:string;status:string;updated_at:number};
export function NeonOutreachPanel({leadId}:{leadId:string}){
 const [drafts,setDrafts]=useState<Draft[]|null>(null),[editing,setEditing]=useState<string|null>(null),[subject,setSubject]=useState(""),[body,setBody]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=async()=>{try{setDrafts((await neonFetch<{drafts:Draft[]}>("/api/outreach?action=list&id="+encodeURIComponent(leadId))).drafts)}catch(e){setError(e instanceof Error?e.message:"Could not load outreach drafts.")}};
 useEffect(()=>{void load()},[leadId]);
 const act=async(action:string,id?:string,method="POST",payload?:unknown)=>{setBusy(true);setError("");try{await neonFetch("/api/outreach?action="+action+(id?"&id="+encodeURIComponent(id):""),{method,body:payload?JSON.stringify(payload):undefined});await load()}catch(e){setError(e instanceof Error?e.message:"Outreach action failed.")}finally{setBusy(false)}};
 const edit=(d:Draft)=>{setEditing(d.id);setSubject(d.subject);setBody(d.body_text)};
 return <div className="border-b border-white/10 p-5">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.16em] text-white/40">Outreach</p><p className="mt-1 text-sm text-white/50">AI drafts require review and approval before Gmail sends anything.</p></div><button disabled={busy} onClick={()=>void act("create",leadId)} className="rounded-lg border border-[#d4af37]/40 bg-[#d4af37]/10 px-3 py-2 text-xs font-semibold text-[#d4af37] disabled:opacity-50">+ Draft follow-up</button></div>
  {error&&<p className="mt-3 rounded-lg border border-red-500/20 bg-red-500/5 p-3 text-xs text-red-300">{error}</p>}
  <div className="mt-4 space-y-3">{drafts===null?<p className="text-sm text-white/40">Loading drafts…</p>:drafts.length===0?<p className="text-sm text-white/35">No outreach drafts yet.</p>:drafts.map(d=><div key={d.id} className="rounded-xl border border-white/10 bg-black/20 p-4">
   <div className="flex flex-wrap justify-between gap-2"><span className="rounded-full border border-white/10 px-2.5 py-1 text-[10px] uppercase tracking-wider text-white/50">{d.status}</span><span className="text-[10px] text-white/30">{new Date(d.updated_at).toLocaleString()}</span></div>
   {editing===d.id?<div className="mt-3 space-y-3"><input value={subject} onChange={e=>setSubject(e.target.value)} className="w-full rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-sm text-white" placeholder="Subject"/><textarea value={body} onChange={e=>setBody(e.target.value)} rows={8} className="w-full rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-sm text-white"/><div className="flex gap-2"><button disabled={busy} onClick={()=>{void act("update",d.id,"PUT",{subject,bodyText:body});setEditing(null)}} className="rounded-lg bg-[#d4af37] px-3 py-2 text-xs font-semibold text-black">Save</button><button onClick={()=>setEditing(null)} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-white/60">Cancel</button></div></div>
   :<><h4 className="mt-3 font-semibold">{d.subject}</h4><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-white/65">{d.body_text}</p><div className="mt-3 flex flex-wrap gap-2">{d.status==="draft"&&<><button onClick={()=>edit(d)} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-white/60">Edit</button><button disabled={busy} onClick={()=>void act("approve",d.id)} className="rounded-lg border border-[#d4af37]/40 px-3 py-2 text-xs text-[#d4af37]">Approve</button></>}{d.status==="approved"&&<><span className="rounded-lg border border-green-500/20 bg-green-500/5 px-3 py-2 text-xs text-green-300">Approved</span><button disabled={busy} onClick={()=>void act("send",d.id)} className="rounded-lg bg-[#d4af37] px-3 py-2 text-xs font-semibold text-black disabled:opacity-50">Send via Gmail</button></>}{d.status==="sent"&&<span className="rounded-lg border border-white/10 px-3 py-2 text-xs text-white/45">Sent via Gmail</span>}</div></>}
  </div>)}</div>
 </div>;
}