import { useEffect, useMemo, useState } from "react"
import { neonFetch } from "../lib/neon-api"

const stages=[["new","New"],["contacted","Contacted"],["qualified","Qualified"],["proposal","Proposal"],["negotiation","Negotiation"],["won","Won"],["lost","Lost"]] as const
type Stage=(typeof stages)[number][0]
const money=(n:number)=>new Intl.NumberFormat(undefined,{maximumFractionDigits:0}).format(n)

export function OpportunityPipeline(){
 const [opportunities,setOpportunities]=useState<any[]>([])
 const [search,setSearch]=useState("")
 const load=async()=>{const r=await neonFetch<{opportunities:any[]}>("/api/opportunities?search="+encodeURIComponent(search));setOpportunities(r.opportunities)}
 useEffect(()=>{void load()},[search])
 const [selected,setSelected]=useState<string|null>(null)
 const [form,setForm]=useState({stage:"new",value:"0",probability:"50",close:"",notes:""})
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return (opportunities??[]).filter(o=>!q||[o.name,o.lead_name,o.company_name,o.lead_email].join(" ").toLowerCase().includes(q))},[opportunities,search])
 const open=(opportunities??[]).filter(o=>o.stage!=="won"&&o.stage!=="lost")
 const openValue=open.reduce((s,o)=>s+o.value,0)
 const weighted=open.reduce((s,o)=>s+o.value*o.probability/100,0)
 const edit=(o:any)=>{setSelected(o.id);setForm({stage:o.stage,value:String(o.value),probability:String(o.probability),close:o.expected_close_at?new Date(o.expectedCloseAt).toISOString().slice(0,10):"",notes:o.notes})}
 const save=async()=>{if(!selected)return;await neonFetch("/api/opportunities?id="+encodeURIComponent(selected),{method:"PUT",body:JSON.stringify({stage:form.stage,value:Number(form.value)||0,probability:Math.min(100,Math.max(0,Number(form.probability)||0)),expectedCloseAt:form.close?new Date(form.close+"T23:59:59").getTime():null,notes:form.notes})});setSelected(null);await load()}
 return <section className="mt-8 overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]">
  <div className="border-b border-white/10 p-5">
   <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.18em] text-[#d4af37]">CRM / Deals</p><h2 className="mt-1 text-xl font-bold">Opportunities</h2><p className="mt-1 text-xs text-white/40">Deal value, probability and expected close dates.</p></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search deals..." className="w-full rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs sm:w-64"/></div>
   <div className="mt-4 grid gap-2 sm:grid-cols-3"><div className="rounded-xl border border-white/10 p-3"><p className="text-[10px] text-white/40">Open pipeline</p><p className="mt-1 text-lg font-bold">{money(openValue)}</p></div><div className="rounded-xl border border-white/10 p-3"><p className="text-[10px] text-white/40">Weighted pipeline</p><p className="mt-1 text-lg font-bold text-[#d4af37]">{money(weighted)}</p></div><div className="rounded-xl border border-white/10 p-3"><p className="text-[10px] text-white/40">Deals</p><p className="mt-1 text-lg font-bold">{opportunities.length}</p></div></div>
  </div>
  <div className="overflow-x-auto"><div className="grid min-w-[1500px] grid-cols-7 divide-x divide-white/10">{stages.map(([key,label])=><div key={key} className="min-h-[280px] bg-black/10"><div className="border-b border-white/10 px-4 py-3 flex justify-between"><span className="text-xs font-semibold">{label}</span><span className="text-[10px] text-white/40">{filtered.filter(o=>o.stage===key).length}</span></div><div className="space-y-3 p-3">{filtered.filter(o=>o.stage===key).map(o=><button key={o.id} type="button" onClick={()=>edit(o)} className="w-full rounded-xl border border-white/10 bg-[#0d0d0d] p-4 text-left hover:bg-white/[0.04]"><div className="flex justify-between gap-2"><span className="truncate text-sm font-semibold">{o.name}</span><span className="text-[10px] text-[#d4af37]">{o.probability}%</span></div><p className="mt-1 truncate text-[10px] text-white/35">{o.companyName||o.leadName}</p><p className="mt-3 text-sm font-semibold">Value: {money(o.value)}</p><p className="mt-1 text-[10px] text-white/35">{o.expectedCloseAt?"Close "+new Date(o.expectedCloseAt).toLocaleDateString():"No close date"}</p></button>)}</div></div>)}</div></div>
  {selected&&<div className="fixed inset-0 z-[60] grid place-items-center bg-black/75 p-4" onClick={()=>setSelected(null)}><div className="w-full max-w-lg rounded-2xl border border-white/10 bg-[#0d0d0d] p-5" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><h3 className="font-bold">Edit opportunity</h3><button onClick={()=>setSelected(null)} className="text-white/40">✕</button></div><div className="mt-4 space-y-3"><div className="grid grid-cols-2 gap-3"><input type="number" value={form.value} onChange={e=>setForm({...form,value:e.target.value})} className="rounded-lg border border-white/10 bg-black/30 p-3 text-sm" placeholder="Value"/><input type="number" min="0" max="100" value={form.probability} onChange={e=>setForm({...form,probability:e.target.value})} className="rounded-lg border border-white/10 bg-black/30 p-3 text-sm" placeholder="Probability %"/></div><select value={form.stage} onChange={e=>setForm({...form,stage:e.target.value})} className="w-full rounded-lg border border-white/10 bg-black/30 p-3 text-sm">{stages.map(([k,l])=><option key={k} value={k}>{l}</option>)}</select><input type="date" value={form.close} onChange={e=>setForm({...form,close:e.target.value})} className="w-full rounded-lg border border-white/10 bg-black/30 p-3 text-sm"/><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} rows={4} className="w-full rounded-lg border border-white/10 bg-black/30 p-3 text-sm" placeholder="Notes"/><button onClick={()=>void save()} className="w-full rounded-lg bg-[#d4af37] p-3 text-sm font-bold text-black">Save opportunity</button></div></div></div>}
 </section>
}