import { useState } from "react"
import { useAction, useConvexAuth, useMutation, useQuery } from "convex/react"
import { api } from "../../convex/_generated/api"

const whatsappUrl=(phone:string,message:string)=>`https://wa.me/${phone.replace(/[^0-9+]/g,"").replace(/^\+/,"")}${message?`?text=${encodeURIComponent(message)}`:""}`
const websiteLabel=(v:string)=>({no_website:"No website",social_only:"Social-only",weak_or_broken:"Weak / broken",has_website:"Has website",unknown:"Needs review"}[v]||"Needs review")
const emailUrl=(email:string,subject:string,body:string)=>`mailto:${email}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`

export function ProspectResearch(){
 const {isAuthenticated}=useConvexAuth()
 const prospects=useQuery(api.research.listRecent,isAuthenticated?{}:"skip") as any[]|undefined
 const leadMachine=useAction(api.research.leadMachine),analyze=useAction(api.research.analyze),enrich=useAction(api.research.enrichContact),sendDraft=useAction(api.outreach.sendApprovedProspectDraft),checkDelivery=useAction(api.outreach.checkProspectDelivery)
 const convert=useMutation(api.research.convertToContact),updateStatus=useMutation(api.research.updateStatus),deleteProspect=useMutation(api.research.deleteProspect),clearResearch=useMutation(api.research.clearResearchHistory),clearHistory=useMutation(api.research.clearProspectsHistory),createDraft=useMutation(api.outreach.createProspectDraft),updateDraft=useMutation(api.outreach.updateProspectDraft),approveDraft=useMutation(api.outreach.approveProspectDraft)
 const [service,setService]=useState("Website Design"),[niche,setNiche]=useState(""),[siteDomain,setSiteDomain]=useState("instagram.com"),[emailDomains,setEmailDomains]=useState("gmail.com yahoo.com hotmail.com outlook.com aol.com"),[customQuery,setCustomQuery]=useState(""),[searchDepth,setSearchDepth]=useState("Standard"),[location,setLocation]=useState(""),[condition,setCondition]=useState("No website"),[avoid,setAvoid]=useState("Agencies, freelancers, directories, competitors")
 const [view,setView]=useState<"all"|"qualified"|"review"|"saved"|"ready">("qualified"),[busy,setBusy]=useState(false),[busyAction,setBusyAction]=useState<Record<string,"analyze"|"contact"|"other"|null>>({}),[message,setMessage]=useState(""),[drafts,setDrafts]=useState<Record<string,any>>({})

 const isOutreachReady=(p:any)=>p.analysisStatus==="ready"&&Boolean(p.contactEmail||p.contactPhone)

 const runMachine=async()=>{setBusy(true);setMessage("");try{const r=await leadMachine({service,niche,location,condition,avoid,siteDomain,emailDomains,customQuery,searchDepth});setMessage(r.results===0?"No candidates survived the qualification rules.":`Found ${r.qualified} qualified prospect${r.qualified===1?"":"s"} and ${r.review} review candidate${r.review===1?"":"s"} from ${r.queries} searches.`);setView(r.qualified>0?"qualified":"review")}catch(e){setMessage(e instanceof Error?e.message:"Lead machine failed.")}finally{setBusy(false)}}
 const act=async(id:string,fn:()=>Promise<any>,success?:string,action:"analyze"|"contact"|"other"="other")=>{setBusyAction(x=>({...x,[id]:action}));setMessage("");try{const r=await fn();if(success)setMessage(success);return r}catch(e){setMessage(e instanceof Error?e.message:"Action failed.");return undefined}finally{setBusyAction(x=>({...x,[id]:null}))}}
 const prepareForOutreach=async(p:any)=>{const r=await act(String(p._id),async()=>{if(p.analysisStatus!=="ready")await analyze({prospectId:p._id});const contact=await enrich({prospectId:p._id});if(contact?.email){const draftId=await createDraft({prospectId:p._id});setDrafts(x=>({...x,[p._id]:{_id:draftId,recipientEmail:contact.email,subject:p.outreachSubject||"A quick idea for "+p.name,bodyText:p.outreachBody||"",status:"draft"}}))}return contact},undefined,"contact");if(!r)return;setMessage(r.email||r.phone?"Ready for outreach: "+(r.email||r.phone)+(r.aiUnavailable?" (AI unavailable; contact came from public search evidence.)":""):"Analysis completed, but no public email or phone was found.");if(r.email||r.phone)setView("ready")}
 const filtered=(prospects||[]).filter((p:any)=>view==="qualified"?p.qualificationStatus==="qualified":view==="review"?p.qualificationStatus==="review":view==="saved"?p.status==="saved":view==="ready"?isOutreachReady(p):true)
 const count=(k:string)=>!prospects?0:k==="qualified"?prospects.filter(p=>p.qualificationStatus==="qualified").length:k==="review"?prospects.filter(p=>p.qualificationStatus==="review").length:k==="saved"?prospects.filter(p=>p.status==="saved").length:prospects.filter(isOutreachReady).length

 return <div className="mt-8 overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]">
  <div className="border-b border-white/10 px-5 py-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">Find potential clients</h2><p className="mt-1 max-w-2xl text-xs leading-5 text-white/40">Search → qualification → website-gap check → public contact discovery → approval-first outreach.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>void act("clear",async()=>clearResearch(),"Research history cleared.")} className="rounded-lg border border-white/10 px-3 py-2 text-[10px] text-white/55">Clear research</button><button onClick={()=>void act("history",async()=>clearHistory(),"Unsaved prospect history cleared.")} className="rounded-lg border border-red-500/20 px-3 py-2 text-[10px] text-red-300">Clear unsaved history</button><span className="rounded-full border border-[#d4af37]/30 px-3 py-1 text-[10px] uppercase tracking-wider text-[#d4af37]">Approval-first</span></div></div></div>
  <div className="border-b border-white/10 p-5"><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">
   <input value={service} onChange={e=>setService(e.target.value)} placeholder="What do you sell?" className="rounded-lg border border-white/10 bg-black/30 px-3 py-3 text-sm text-white"/>
   <input value={niche} onChange={e=>setNiche(e.target.value)} placeholder="Niche / work e.g. Dentist" className="rounded-lg border border-white/10 bg-black/30 px-3 py-3 text-sm text-white"/>
   <input value={siteDomain} onChange={e=>setSiteDomain(e.target.value)} placeholder="Site e.g. instagram.com" className="rounded-lg border border-white/10 bg-black/30 px-3 py-3 text-sm text-white"/>
   <input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Where? e.g. Port Harcourt, Nigeria" className="rounded-lg border border-white/10 bg-black/30 px-3 py-3 text-sm text-white"/>
   <select value={condition} onChange={e=>setCondition(e.target.value)} className="rounded-lg border border-white/10 bg-black/30 px-3 py-3 text-sm text-white"><option>No website</option><option>Weak/outdated website</option><option>Either</option><option>Any potential buyer</option></select>
   <input value={emailDomains} onChange={e=>setEmailDomains(e.target.value)} placeholder="@gmail.com @yahoo.com ..." className="rounded-lg border border-white/10 bg-black/30 px-3 py-3 text-sm text-white"/>
  </div><input value={avoid} onChange={e=>setAvoid(e.target.value)} placeholder="Who should we avoid?" className="mt-3 w-full rounded-lg border border-white/10 bg-black/30 px-3 py-3 text-sm text-white"/>
  <div className="mt-3 flex flex-wrap items-center gap-3"><label className="text-[10px] uppercase tracking-wider text-white/35">Search depth</label><select value={searchDepth} onChange={e=>setSearchDepth(e.target.value)} className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs text-white"><option>Quick</option><option>Standard</option><option>Deep</option></select></div>
  <div className="mt-4 rounded-xl border border-[#d4af37]/20 bg-black/20 p-4"><p className="text-xs font-semibold uppercase tracking-wider text-[#d4af37]">Google Query</p><textarea value={customQuery} onChange={e=>setCustomQuery(e.target.value)} placeholder={'Optional exact Google query. Example: site:instagram.com "dentist" "@gmail.com"'} rows={3} className="mt-2 w-full rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs text-white"/></div>
  <div className="mt-4 flex flex-wrap items-center gap-3"><button onClick={()=>void runMachine()} disabled={busy||!service.trim()||!niche.trim()} className="min-h-11 rounded-lg bg-[#d4af37] px-6 py-2 text-sm font-semibold text-black disabled:opacity-40">{busy?"Finding & qualifying…":"Find Prospects"}</button><span className="text-[11px] text-white/35">Nothing is contacted automatically. Approval is required before email sending.</span></div></div>
  {message&&<p className="border-b border-white/10 px-5 py-3 text-xs text-white/60">{message}</p>}
  <div className="grid grid-cols-2 gap-px border-b border-white/10 bg-white/5 sm:grid-cols-4">{[["qualified","Qualified"],["review","Review"],["saved","Saved"],["ready","Ready for outreach"]].map(([k,l])=><button key={k} onClick={()=>setView(k as any)} className={"bg-black/20 px-3 py-3 text-left "+(view===k?"bg-white/[0.06]":"")}><span className="block text-[10px] uppercase tracking-wider text-white/35">{l}</span><span className="mt-1 block text-lg font-semibold text-white">{count(k)}</span></button>)}</div>
  <div className="border-b border-white/10 px-5 py-3"><button onClick={()=>setView("all")} className={"rounded-lg px-3 py-2 text-xs "+(view==="all"?"bg-white/10 text-white":"border border-white/10 text-white/45")}>All</button><p className="mt-2 text-[11px] text-white/35">Search → qualify → Save → Prepare for outreach (analyze + contact) → Edit draft → Approve → send.</p></div>
  <div className="divide-y divide-white/10">{prospects===undefined?<p className="p-6 text-sm text-white/40">Loading prospects…</p>:filtered.length===0?<p className="p-6 text-sm text-white/40">No prospects in this view yet.</p>:filtered.map((p:any)=>{const d=drafts[p._id],actionBusy=busyAction[String(p._id)]||null,working=actionBusy!==null,analyzing=actionBusy==="analyze",findingContact=actionBusy==="contact",ready=isOutreachReady(p);return <article key={p._id} className="p-5">
   <div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><a href={p.url} target="_blank" rel="noreferrer" className="font-semibold text-[#d4af37] hover:underline">{p.name}</a><p className="mt-1 break-all text-xs text-white/35">{p.url}</p></div><div className="flex flex-wrap gap-2"><span className={"rounded-full border px-2.5 py-1 text-[10px] uppercase tracking-wider "+(p.qualificationStatus==="qualified"?"border-green-500/20 text-green-300":p.qualificationStatus==="review"?"border-amber-500/20 text-amber-200":"border-white/10 text-white/45")}>{p.qualificationStatus||"unclassified"}</span>{p.websiteStatus&&<span className="rounded-full border border-cyan-400/20 px-2.5 py-1 text-[10px] text-cyan-200">{websiteLabel(p.websiteStatus)}</span>}{p.status==="saved"&&<span className="rounded-full border border-green-500/20 px-2.5 py-1 text-[10px] text-green-300">Saved</span>}{ready&&<span className="rounded-full border border-[#d4af37]/30 px-2.5 py-1 text-[10px] text-[#d4af37]">Ready for outreach</span>}</div></div>
   <p className="mt-3 text-sm leading-6 text-white/60">{p.snippet||"No search summary returned."}</p>{p.qualificationReason&&<p className="mt-3 text-xs leading-5 text-white/45"><b className="text-white/70">Why it surfaced:</b> {p.qualificationReason}</p>}{(p.contactEmail||p.contactPhone)&&<p className="mt-2 text-xs text-white/50"><b className="text-white/70">Public contact:</b> {p.contactName?p.contactName+" — ":""}{p.contactEmail||p.contactPhone}{p.contactEmail&&p.contactPhone?" · "+p.contactPhone:""}</p>}{p.contactEvidence&&<p className="mt-2 text-xs text-white/40"><b className="text-white/60">Contact evidence:</b> {p.contactEvidence}</p>}
   {p.analysisStatus==="ready"&&<div className="mt-4 rounded-xl border border-[#d4af37]/15 bg-black/20 p-4 space-y-2 text-sm"><p><b className="text-white/70">Fit:</b> <span className="text-white/55">{p.fitReason}</span></p><p><b className="text-white/70">Potential need:</b> <span className="text-white/55">{p.painPoint}</span></p>{p.outreachSubject&&<div className="pt-2"><p className="text-xs uppercase tracking-wider text-white/35">AI outreach draft</p><p className="mt-1 font-medium text-white/75">{p.outreachSubject}</p><p className="mt-2 whitespace-pre-wrap text-white/55">{p.outreachBody}</p></div>}</div>}
   <div className="mt-4 flex flex-wrap gap-2">
    {p.status!=="saved"&&<button onClick={()=>void act(String(p._id),()=>updateStatus({prospectId:p._id,status:"saved"}),"Prospect saved.")} disabled={working} className="rounded-lg border border-green-500/20 px-3 py-2 text-xs text-green-300">Save prospect</button>}{p.status==="saved"&&<span className="rounded-lg border border-green-500/20 bg-green-500/5 px-3 py-2 text-xs text-green-300">Saved</span>}
    <button onClick={()=>void act(String(p._id),()=>updateStatus({prospectId:p._id,status:"discarded"}),"Prospect discarded.")} disabled={working} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-white/45">Discard</button>
    <button onClick={()=>{if(confirm("Delete this prospect and related outreach data? This cannot be undone."))void act(String(p._id),()=>deleteProspect({prospectId:p._id}),"Prospect deleted.")}} disabled={working} className="rounded-lg border border-red-500/20 px-3 py-2 text-xs text-red-300">Delete</button>
    <button onClick={()=>void act(String(p._id),()=>analyze({prospectId:p._id}),"Analysis ready.","analyze")} disabled={working} className="rounded-lg border border-[#d4af37]/30 px-3 py-2 text-xs text-[#d4af37]">{analyzing?"Analyzing…":p.analysisStatus==="ready"?"Re-analyze":"Analyze & draft"}</button>
    <button onClick={()=>void prepareForOutreach(p)} disabled={working} className="rounded-lg border border-cyan-400/30 px-3 py-2 text-xs text-cyan-200">{findingContact?"Preparing for outreach…":ready?"Re-check contact":"Prepare for outreach"}</button>
    {p.contactStatus==="verified"&&(p.contactEmail||p.contactPhone)&&<button onClick={()=>void act(String(p._id),()=>convert({prospectId:p._id}),"Prospect added to CRM.")} disabled={working} className="rounded-lg border border-purple-400/30 px-3 py-2 text-xs text-purple-200">Add to CRM</button>}
    {p.contactEmail&&<a href={emailUrl(p.contactEmail,d?.subject||p.outreachSubject||"A quick idea for "+p.name,d?.bodyText||p.outreachBody||"Hello, I came across your business and wanted to ask about your website needs.")} className="rounded-lg bg-[#d4af37] px-3 py-2 text-xs font-semibold text-black">Email</a>}{p.contactPhone&&<a href={whatsappUrl(p.contactPhone,d?.bodyText||p.outreachBody||"Hello, I came across your business and wanted to ask about your website needs.")} target="_blank" rel="noreferrer" className="rounded-lg bg-green-600 px-3 py-2 text-xs font-semibold text-white">WhatsApp</a>}
    
   </div>
   {d&&<div className="mt-4 rounded-xl border border-white/10 bg-black/20 p-4"><div className="flex items-center justify-between gap-2"><p className="text-xs uppercase tracking-wider text-white/35">Outreach approval</p><span className="text-[10px] uppercase tracking-wider text-[#d4af37]">{d.status}</span></div><p className="mt-2 text-xs text-white/35">To: {d.recipientEmail}</p><input value={d.subject} onChange={e=>setDrafts(x=>({...x,[p._id]:{...d,subject:e.target.value}}))} disabled={d.status==="sent"} className="mt-3 w-full rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-sm text-white"/><textarea value={d.bodyText} onChange={e=>setDrafts(x=>({...x,[p._id]:{...d,bodyText:e.target.value}}))} disabled={d.status==="sent"} rows={7} className="mt-2 w-full rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-sm text-white"/>
    {d.deliveryStatus==="undeliverable"&&<div className="mt-3 rounded-lg border border-red-500/20 bg-red-500/5 px-3 py-2 text-xs text-red-300"><b>Undeliverable</b> — do not resend to this address.{d.deliveryError&&<p className="mt-1 text-red-300/70">{d.deliveryError}</p>}</div>}
    <div className="mt-3 flex flex-wrap gap-2">{d.status!=="sent"&&<button onClick={()=>void act(String(p._id),()=>updateDraft({draftId:d._id,subject:d.subject,bodyText:d.bodyText}),"Draft saved.")} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-white/70">Save edits</button>}{d.status==="draft"&&<button onClick={()=>void act(String(p._id),()=>approveDraft({draftId:d._id}),"Approved and placed in the one-hour queue.")} className="rounded-lg bg-green-600 px-3 py-2 text-xs font-semibold text-white">Approve</button>}{d.status==="approved"&&<button onClick={()=>void act(String(p._id),()=>sendDraft({draftId:d._id}),"Email sent via Gmail.")} className="rounded-lg bg-[#d4af37] px-3 py-2 text-xs font-semibold text-black">Send now</button>}{d.status==="sent"&&d.deliveryStatus!=="undeliverable"&&<button onClick={()=>void act(String(p._id),()=>checkDelivery({draftId:d._id}),"Delivery check completed.")} className="rounded-lg border border-cyan-400/30 px-3 py-2 text-xs text-cyan-200">Check delivery</button>}</div></div>}
  </article>})}</div>
 </div>
}
