import { useEffect,useMemo,useState } from "react";
import { neonFetch } from "../lib/neon-api";
const stages=[["new","New Lead"],["contacted","Contacted"],["qualified","Qualified"],["won","Won"],["lost","Lost"]] as const;
export function SalesPipeline(){
 const [leads,setLeads]=useState<any[]|undefined>(undefined),[search,setSearch]=useState(""),[busy,setBusy]=useState<string|null>(null);
 const load=async()=>{const r=await neonFetch<any>("/api/leads?resource=leads");setLeads(r.leads||[])};useMemo(()=>{void load().catch(()=>setLeads([]))},[]);
 const filtered=(leads||[]).filter(l=>!search.trim()||[l.name,l.email,l.company,l.request].join(" ").toLowerCase().includes(search.toLowerCase()));
 const move=async(id:string,status:string)=>{setBusy(id);try{await neonFetch("/api/leads?resource=lead-status&id="+encodeURIComponent(id),{method:"PATCH",body:JSON.stringify({status})});await load()}finally{setBusy(null)}};
 const convert=async(id:string)=>{await neonFetch("/api/opportunities?action=from-lead&leadId="+encodeURIComponent(id),{method:"POST"});};
 return <section className="mt-8 overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]"><div className="border-b border-white/10 p-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.18em] text-[#d4af37]">CRM / Opportunities</p><h2 className="mt-1 text-xl font-bold">Sales Pipeline</h2><p className="mt-1 max-w-2xl text-xs leading-5 text-white/40">Move every enquiry through the same sales journey.</p></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search contacts, companies..." className="w-full rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs text-white outline-none sm:w-64"/></div></div><div className="overflow-x-auto"><div className="grid min-w-[1120px] grid-cols-5 divide-x divide-white/10">{stages.map(([key,label])=>{const items=filtered.filter(l=>l.status===key);return <div key={key} className="min-h-[320px] bg-black/10"><div className="border-b border-white/10 px-4 py-3"><div className="flex items-center justify-between"><span className="text-xs font-semibold">{label}</span><span className="rounded-full border border-white/10 px-2 py-0.5 text-[10px] text-white/45">{items.length}</span></div></div><div className="space-y-3 p-3">{items.map(l=><article key={l.id} className="rounded-xl border border-white/10 bg-[#0d0d0d] p-4"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><h3 className="truncate text-sm font-semibold">{l.name}</h3><p className="mt-1 truncate text-[10px] text-white/35">{l.company||l.email}</p></div><span className="text-[10px] text-white/25">#{String(l.id).slice(-5)}</span></div><p className="mt-3 line-clamp-3 text-xs leading-5 text-white/55">{l.request}</p>{(l.budget||l.timeline)&&<div className="mt-3 flex flex-wrap gap-1.5">{l.budget&&<span className="rounded-full border border-white/10 px-2 py-1 text-[9px] text-white/40">{l.budget}</span>}{l.timeline&&<span className="rounded-full border border-white/10 px-2 py-1 text-[9px] text-white/40">{l.timeline}</span>}</div>}<button type="button" onClick={()=>void convert(l.id)} className="mt-3 w-full rounded-lg border border-[#d4af37]/25 bg-[#d4af37]/10 px-2 py-2 text-[10px] font-semibold text-[#d4af37]">Convert to deal</button><select value={l.status} disabled={busy===String(l.id)} onChange={e=>void move(l.id,e.target.value)} className="mt-4 w-full rounded-lg border border-white/10 bg-black/40 px-2 py-2 text-[10px] text-white/60 outline-none">{stages.map(([k,lab])=><option key={k} value={k}>Move to {lab}</option>)}</select></article>)}</div></div>})}</div></div></section>
}
