import { useState } from "react"
import { useConvexAuth, useMutation, useQuery } from "convex/react"
import { api } from "../../convex/_generated/api"
import type { Id } from "../../convex/_generated/dataModel"

type Step={type:"create_task"|"add_note"|"create_email_draft"|"update_stage"|"branch"|"goal";value:string;delayMinutes:number;trueStep?:number;falseStep?:number}
const labels={create_task:"Create task",add_note:"Add CRM note",create_email_draft:"Create email draft",update_stage:"Move lead stage",branch:"Branch / condition",goal:"Goal / stop workflow"} as const
const triggers={lead_created:"Lead created",stage_changed:"Pipeline stage changed",appointment_booked:"Appointment booked",invoice_paid:"Invoice paid",form_submitted:"Form submitted",review_completed:"Review completed"} as const
const conditions=["any","new","contacted","qualified","won","lost"] as const

export function WorkflowBuilder(){
 const {isAuthenticated}=useConvexAuth()
 const rows=useQuery(api.workflows.list,isAuthenticated?{}:"skip")||[]
 const create=useMutation(api.workflows.create),toggle=useMutation(api.workflows.toggle)
 const [name,setName]=useState(""),[trigger,setTrigger]=useState<keyof typeof triggers>("lead_created"),[condition,setCondition]=useState<(typeof conditions)[number]>("any"),[goal,setGoal]=useState("")
 const [steps,setSteps]=useState<Step[]>([{type:"create_task",value:"Follow up with the lead",delayMinutes:0}]),[error,setError]=useState("")
 const update=(i:number,p:Partial<Step>)=>setSteps(s=>s.map((x,n)=>n===i?{...x,...p}:x))
 const add=async()=>{if(!name.trim()||!steps[0]?.value.trim())return;try{const first=steps[0];await create({name:name.trim(),trigger,condition,action:first.type==="update_stage"||first.type==="branch"||first.type==="goal"?"create_task":first.type,actionValue:first.value,steps,goal:goal.trim()||undefined});setName("");setGoal("");setSteps([{type:"create_task",value:"Follow up with the lead",delayMinutes:0}])}catch(e){setError(e instanceof Error?e.message:"Unable to create workflow")}}
 const flip=async(w:any)=>{try{await toggle({workflowId:w._id as Id<"workflows">,enabled:!w.enabled})}catch(e){setError(e instanceof Error?e.message:"Unable to update workflow")}}
 return <section className="mt-8 overflow-hidden rounded-2xl border border-white/10 bg-white/[0.03]">
  <div className="border-b border-white/10 p-5"><p className="text-xs uppercase tracking-[.18em] text-[#d4af37]">Automation Engine</p><h2 className="mt-1 text-xl font-bold">Trigger → Conditions → Actions → Delays → Branches → Goals</h2><p className="mt-1 text-xs text-white/40">Build multi-step automations with delayed actions and conditional branches.</p></div>
  {error&&<div className="mx-5 mt-4 rounded-xl border border-red-400/20 bg-red-400/5 px-3 py-2 text-xs text-red-200">{error}</div>}
  <div className="grid gap-4 p-5 md:grid-cols-4"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Workflow name" className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs"/><select value={trigger} onChange={e=>setTrigger(e.target.value as keyof typeof triggers)} className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs">{Object.entries(triggers).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={condition} onChange={e=>setCondition(e.target.value as any)} className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs">{conditions.map(v=><option key={v} value={v}>{v==="any"?"Any lead stage":"Stage: "+v}</option>)}</select><input value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Goal: status|equals|won" className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs"/></div>
  <div className="space-y-3 px-5 pb-5">{steps.map((step,i)=><div key={i} className="rounded-xl border border-white/10 bg-black/20 p-4"><div className="mb-3 flex items-center justify-between"><span className="text-[10px] uppercase tracking-wider text-white/35">Step {i+1}</span>{steps.length>1&&<button onClick={()=>setSteps(s=>s.filter((_,n)=>n!==i))} className="text-[10px] text-red-300">Remove</button>}</div><div className="grid gap-2 md:grid-cols-[1fr_1.4fr_130px]"><select value={step.type} onChange={e=>update(i,{type:e.target.value as Step["type"]})} className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs">{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{step.type==="update_stage"?<select value={step.value} onChange={e=>update(i,{value:e.target.value})} className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs"><option value="contacted">Contacted</option><option value="qualified">Qualified</option><option value="won">Won</option><option value="lost">Lost</option></select>:step.type==="branch"?<select value={step.value} onChange={e=>update(i,{value:e.target.value})} className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs"><option value="status|equals|new">If status = new</option><option value="status|equals|qualified">If status = qualified</option><option value="status|equals|won">If status = won</option></select>:step.type==="goal"?<select value={step.value} onChange={e=>update(i,{value:e.target.value})} className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs"><option value="status|equals|won">Goal: status = won</option><option value="status|equals|qualified">Goal: status = qualified</option></select>:<input value={step.value} onChange={e=>update(i,{value:e.target.value})} placeholder="Action instruction..." className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs"/>}<input type="number" min="0" value={step.delayMinutes} onChange={e=>update(i,{delayMinutes:Number(e.target.value)||0})} placeholder="Delay (min)" className="rounded-lg border border-white/10 bg-black/30 px-3 py-2 text-xs"/></div></div>)}
  <div className="flex flex-wrap gap-2"><button onClick={()=>setSteps(s=>[...s,{type:"add_note",value:"Add a CRM note",delayMinutes:0}])} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-white/55">+ Add step</button><button onClick={()=>void add()} className="rounded-lg bg-[#d4af37] px-4 py-2 text-xs font-bold text-black">Create workflow</button></div></div>
  <div className="divide-y divide-white/10 border-t border-white/10">{!rows.length?<p className="p-5 text-xs text-white/40">No workflows yet.</p>:rows.map((w:any)=><div key={w._id} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="text-sm font-semibold">{w.name}</p><p className="mt-1 text-[11px] text-white/40">{triggers[w.trigger as keyof typeof triggers]||w.trigger} → {w.condition} → {w.steps?.length?w.steps.length+" steps":w.action}</p></div><button onClick={()=>void flip(w)} className={"rounded-full px-3 py-1 text-[10px] font-semibold "+(w.enabled?"bg-green-500/15 text-green-300":"bg-white/10 text-white/40")}>{w.enabled?"Enabled":"Disabled"}</button></div>)}</div>
 </section>
}
