/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ReviewIdRouteImport } from './routes/review/$id'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as InvoiceIdRouteImport } from './routes/invoice.$id'
import { Route as FormFormIdRouteImport } from './routes/form.$formId'
import { Route as BookBookingTypeIdRouteImport } from './routes/book.$bookingTypeId'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminPipelineRouteImport } from './routes/admin/pipeline'
import { Route as AdminOutreachRouteImport } from './routes/admin/outreach'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminConversationsRouteImport } from './routes/admin/conversations'
import { Route as AdminContactsRouteImport } from './routes/admin/contacts'
import { Route as AdminCompaniesRouteImport } from './routes/admin/companies'
import { Route as AdminCalendarRouteImport } from './routes/admin/calendar'
import { Route as AdminBillingRouteImport } from './routes/admin/billing'
import { Route as AdminAutomationRouteImport } from './routes/admin/automation'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ReviewIdRoute = ReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceIdRoute = InvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FormFormIdRoute = FormFormIdRouteImport.update({
  id: '/form/$formId',
  path: '/form/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBookingTypeIdRoute = BookBookingTypeIdRouteImport.update({
  id: '/book/$bookingTypeId',
  path: '/book/$bookingTypeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPipelineRoute = AdminPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOutreachRoute = AdminOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConversationsRoute = AdminConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutomationRoute = AdminAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/outreach': typeof AdminOutreachRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/book/$bookingTypeId': typeof BookBookingTypeIdRoute
  '/form/$formId': typeof FormFormIdRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/p/$slug': typeof PSlugRoute
  '/review/$id': typeof ReviewIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/outreach': typeof AdminOutreachRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/book/$bookingTypeId': typeof BookBookingTypeIdRoute
  '/form/$formId': typeof FormFormIdRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/p/$slug': typeof PSlugRoute
  '/review/$id': typeof ReviewIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/companies': typeof AdminCompaniesRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/outreach': typeof AdminOutreachRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/api/$': typeof ApiSplatRoute
  '/book/$bookingTypeId': typeof BookBookingTypeIdRoute
  '/form/$formId': typeof FormFormIdRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/p/$slug': typeof PSlugRoute
  '/review/$id': typeof ReviewIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/automation'
    | '/admin/billing'
    | '/admin/calendar'
    | '/admin/companies'
    | '/admin/contacts'
    | '/admin/conversations'
    | '/admin/leads'
    | '/admin/outreach'
    | '/admin/pipeline'
    | '/admin/reports'
    | '/admin/settings'
    | '/api/$'
    | '/book/$bookingTypeId'
    | '/form/$formId'
    | '/invoice/$id'
    | '/p/$slug'
    | '/review/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/automation'
    | '/admin/billing'
    | '/admin/calendar'
    | '/admin/companies'
    | '/admin/contacts'
    | '/admin/conversations'
    | '/admin/leads'
    | '/admin/outreach'
    | '/admin/pipeline'
    | '/admin/reports'
    | '/admin/settings'
    | '/api/$'
    | '/book/$bookingTypeId'
    | '/form/$formId'
    | '/invoice/$id'
    | '/p/$slug'
    | '/review/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/automation'
    | '/admin/billing'
    | '/admin/calendar'
    | '/admin/companies'
    | '/admin/contacts'
    | '/admin/conversations'
    | '/admin/leads'
    | '/admin/outreach'
    | '/admin/pipeline'
    | '/admin/reports'
    | '/admin/settings'
    | '/api/$'
    | '/book/$bookingTypeId'
    | '/form/$formId'
    | '/invoice/$id'
    | '/p/$slug'
    | '/review/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  BookBookingTypeIdRoute: typeof BookBookingTypeIdRoute
  FormFormIdRoute: typeof FormFormIdRoute
  InvoiceIdRoute: typeof InvoiceIdRoute
  PSlugRoute: typeof PSlugRoute
  ReviewIdRoute: typeof ReviewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/review/$id': {
      id: '/review/$id'
      path: '/review/$id'
      fullPath: '/review/$id'
      preLoaderRoute: typeof ReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$id': {
      id: '/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/invoice/$id'
      preLoaderRoute: typeof InvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form/$formId': {
      id: '/form/$formId'
      path: '/form/$formId'
      fullPath: '/form/$formId'
      preLoaderRoute: typeof FormFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$bookingTypeId': {
      id: '/book/$bookingTypeId'
      path: '/book/$bookingTypeId'
      fullPath: '/book/$bookingTypeId'
      preLoaderRoute: typeof BookBookingTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pipeline': {
      id: '/admin/pipeline'
      path: '/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AdminPipelineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/outreach': {
      id: '/admin/outreach'
      path: '/outreach'
      fullPath: '/admin/outreach'
      preLoaderRoute: typeof AdminOutreachRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conversations': {
      id: '/admin/conversations'
      path: '/conversations'
      fullPath: '/admin/conversations'
      preLoaderRoute: typeof AdminConversationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/companies': {
      id: '/admin/companies'
      path: '/companies'
      fullPath: '/admin/companies'
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/automation': {
      id: '/admin/automation'
      path: '/automation'
      fullPath: '/admin/automation'
      preLoaderRoute: typeof AdminAutomationRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAutomationRoute: typeof AdminAutomationRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCompaniesRoute: typeof AdminCompaniesRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminConversationsRoute: typeof AdminConversationsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminOutreachRoute: typeof AdminOutreachRoute
  AdminPipelineRoute: typeof AdminPipelineRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAutomationRoute: AdminAutomationRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCompaniesRoute: AdminCompaniesRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminConversationsRoute: AdminConversationsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminOutreachRoute: AdminOutreachRoute,
  AdminPipelineRoute: AdminPipelineRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  BookBookingTypeIdRoute: BookBookingTypeIdRoute,
  FormFormIdRoute: FormFormIdRoute,
  InvoiceIdRoute: InvoiceIdRoute,
  PSlugRoute: PSlugRoute,
  ReviewIdRoute: ReviewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
